// Package v20260731 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v20260731

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"

	externalRef0 "github.com/F5Networks/terraform-provider-f5ads/internal/provider/clients/naas"
)

// Defines values for NGINXaaSConfigPayloadType.
const (
	NginxConfigPayloadAwsSecretsManager   NGINXaaSConfigPayloadType = "aws_secrets_manager"
	NginxConfigPayloadGoogleSecretManager NGINXaaSConfigPayloadType = "google_secret_manager"
	NginxConfigPayloadManagedCertificate  NGINXaaSConfigPayloadType = "managed_certificate"
	NginxConfigPayloadManagedKey          NGINXaaSConfigPayloadType = "managed_key"
)

// Valid indicates whether the value is a known member of the NGINXaaSConfigPayloadType enum.
func (e NGINXaaSConfigPayloadType) Valid() bool {
	switch e {
	case NginxConfigPayloadAwsSecretsManager:
		return true
	case NginxConfigPayloadGoogleSecretManager:
		return true
	case NginxConfigPayloadManagedCertificate:
		return true
	case NginxConfigPayloadManagedKey:
		return true
	default:
		return false
	}
}

// NGINXConfig defines model for NGINXConfig.
type NGINXConfig struct {
	// Aux An array of auxiliary directory contents related to the NGINX configuration.
	Aux *[]externalRef0.DirectoryWithFileContent `json:"aux,omitempty"`

	// ConfPath The full path to the main NGINX configuration file. This corresponds to the `--conf-path` parameter used in the NGINX binary.
	ConfPath externalRef0.ConfigPath `json:"conf_path"`

	// ConfigVersion A hash that uniquely identifies the contents of the config object. Can be used to detect change when updating the NginxConfig.
	ConfigVersion *string `json:"config_version,omitempty"`

	// Configs An array of directories containing NGINX configuration files.
	Configs []externalRef0.DirectoryWithFileContent `json:"configs"`

	// ObjectId A globally unique identifier for the NGINX Config object.
	ObjectId externalRef0.NginxConfigObjectID `json:"object_id"`

	// Payloads An array of payloads that track the file paths of each SSL certificates and key, indicating where to deploy
	// them onto the data plane instance.
	// * If the `type` is `managed_certificate` or `managed_key`, you need to specify an `object_id`.
	//   * The `object_id` must represent a managed certificate object, or a `400 Bad Request` is returned.
	//   * The `contents` field is optional and is ignored if included.
	// * NGINXaaS manages deployed file paths only for managed certificates and keys. If you don't want
	// them to be managed by NGINXaaS, `inline_content` and `inline_secret` can be used for certificates or
	// keys, respectively. When you retrieve certificate deployment details, only the file paths of managed
	// certificates and keys will be shown.
	// * If you use `inline_content` and `inline_secret` in your NGINX configuration, NGINXaaS
	// will detect them. When they are used as SSL directives of the NGINX configuration
	// for certificates and keys, the certificates will be listed as `unmanaged_certificate` in the certificate
	// deployment details.
	// * if the type is `google_secret_manager` or `aws_secrets_manager`, you need to specify the secret
	// `resource_name`.
	Payloads *NGINXaaSConfigPayloads `json:"payloads,omitempty"`
}

// NGINXaaSConfigPayload Details of Aux File Payload that goes with an NGINX configuration. Provide hints for the backend system on
// additional file contents that should be part of the NGINX Config Publication.
// Can be used to deploy files related to SSL certificates, to a data plane instance.
type NGINXaaSConfigPayload struct {
	// Contents The base64-encoded contents of the file.
	Contents *externalRef0.NginxConfigPayloadContents `json:"contents,omitempty"`

	// ObjectId A globally unique identifier for the valid payload object reference.
	ObjectId *externalRef0.PayloadObjectID        `json:"object_id,omitempty"`
	Paths    externalRef0.NginxConfigPayloadPaths `json:"paths"`

	// ResourceName The resource name of any external resources.
	ResourceName *string `json:"resource_name,omitempty"`

	// Type Types of Aux File Payload:
	//   - managed_certificate - indicates public certificates managed by NGINXaaS.
	//   - managed_key - indicates a private key managed by NGINXaaS.
	//   - google_secret_manager - indicates a secret stored in Google Secret Manager.
	//   - aws_secrets_manager - indicates a secret stored in AWS Secrets Manager.
	Type NGINXaaSConfigPayloadType `json:"type"`
}

// NGINXaaSConfigPayloadType Types of Aux File Payload:
//   - managed_certificate - indicates public certificates managed by NGINXaaS.
//   - managed_key - indicates a private key managed by NGINXaaS.
//   - google_secret_manager - indicates a secret stored in Google Secret Manager.
//   - aws_secrets_manager - indicates a secret stored in AWS Secrets Manager.
type NGINXaaSConfigPayloadType string

// NGINXaaSConfigPayloads An array of payloads that track the file paths of each SSL certificates and key, indicating where to deploy
// them onto the data plane instance.
// * If the `type` is `managed_certificate` or `managed_key`, you need to specify an `object_id`.
//   - The `object_id` must represent a managed certificate object, or a `400 Bad Request` is returned.
//   - The `contents` field is optional and is ignored if included.
//
// * NGINXaaS manages deployed file paths only for managed certificates and keys. If you don't want
// them to be managed by NGINXaaS, `inline_content` and `inline_secret` can be used for certificates or
// keys, respectively. When you retrieve certificate deployment details, only the file paths of managed
// certificates and keys will be shown.
// * If you use `inline_content` and `inline_secret` in your NGINX configuration, NGINXaaS
// will detect them. When they are used as SSL directives of the NGINX configuration
// for certificates and keys, the certificates will be listed as `unmanaged_certificate` in the certificate
// deployment details.
// * if the type is `google_secret_manager` or `aws_secrets_manager`, you need to specify the secret
// `resource_name`.
type NGINXaaSConfigPayloads = []NGINXaaSConfigPayload

// NGINXaaSConfigRequest defines model for NGINXaaSConfigRequest.
type NGINXaaSConfigRequest struct {
	// Aux An array of auxiliary directory contents related to the NGINX configuration. When auxiliary contents are
	// provided, they become the authoritative source of non-NGINX configuration content. Please ensure the
	// provided contents are complete, missing files that are referenced in the NGINX configuration can cause
	// NGINX reload failure. When not provided, the previous known auxiliary contents will be used as part of
	// publish.
	Aux *[]externalRef0.DirectoryRequestWithFileContent `json:"aux,omitempty"`

	// ConfPath The full path to the main NGINX configuration file. This corresponds to the `--conf-path` parameter used in the NGINX binary.
	ConfPath *externalRef0.ConfigPath `json:"conf_path,omitempty"`

	// ConfigVersion A hash that uniquely identifies the contents of the config object. Can be used to detect change when updating the NginxConfig.
	ConfigVersion *string `json:"config_version,omitempty"`

	// Configs An array of directories containing NGINX configuration files.
	Configs []externalRef0.DirectoryRequestWithFileContent `json:"configs"`

	// Payloads An array of payloads that track the file paths of each SSL certificates and key, indicating where to deploy
	// them onto the data plane instance.
	// * If the `type` is `managed_certificate` or `managed_key`, you need to specify an `object_id`.
	//   * The `object_id` must represent a managed certificate object, or a `400 Bad Request` is returned.
	//   * The `contents` field is optional and is ignored if included.
	// * NGINXaaS manages deployed file paths only for managed certificates and keys. If you don't want
	// them to be managed by NGINXaaS, `inline_content` and `inline_secret` can be used for certificates or
	// keys, respectively. When you retrieve certificate deployment details, only the file paths of managed
	// certificates and keys will be shown.
	// * If you use `inline_content` and `inline_secret` in your NGINX configuration, NGINXaaS
	// will detect them. When they are used as SSL directives of the NGINX configuration
	// for certificates and keys, the certificates will be listed as `unmanaged_certificate` in the certificate
	// deployment details.
	// * if the type is `google_secret_manager` or `aws_secrets_manager`, you need to specify the secret
	// `resource_name`.
	Payloads *NGINXaaSConfigPayloads `json:"payloads,omitempty"`
}

// NginxConfig defines model for NginxConfig.
type NginxConfig struct {
	CreatedAt time.Time `json:"created_at"`

	// Description Description of a resource.
	Description *externalRef0.NginxaasDescription `json:"description,omitempty"`

	// LatestVersion NGINX config version object id
	LatestVersion externalRef0.NginxaasNginxConfigVersionObjectID `json:"latest_version"`
	ModifiedAt    time.Time                                       `json:"modified_at"`
	Name          NginxConfigName                                 `json:"name"`

	// ObjectId A globally unique identifier for the NGINX config.
	ObjectId externalRef0.NginxaasNginxConfigObjectID `json:"object_id"`

	// OrganizationId NGINXaaS organization id
	OrganizationId externalRef0.NginxaasOrganizationID `json:"organization_id"`
}

// NginxConfigCreateRequest defines model for NginxConfigCreateRequest.
type NginxConfigCreateRequest struct {
	Config NGINXaaSConfigRequest `json:"config"`

	// Description Description of a resource.
	Description *externalRef0.NginxaasDescription `json:"description,omitempty"`
	Name        NginxConfigName                   `json:"name"`
}

// NginxConfigListResponse List of Nginx configs.
type NginxConfigListResponse struct {
	// Count The total number of Nginx configs returned.
	Count int           `json:"count"`
	Items []NginxConfig `json:"items"`
}

// NginxConfigListVersionsResponse List of Nginx configs.
type NginxConfigListVersionsResponse struct {
	// Count The total number of Nginx configs returned.
	Count int                      `json:"count"`
	Items []NginxConfigVersionMeta `json:"items"`
}

// NginxConfigName defines model for NginxConfigName.
type NginxConfigName = string

// NginxConfigReplaceRequest defines model for NginxConfigReplaceRequest.
type NginxConfigReplaceRequest struct {
	Config NGINXaaSConfigRequest `json:"config"`

	// Description Description of a resource.
	Description *externalRef0.NginxaasDescription `json:"description,omitempty"`
}

// NginxConfigUpdateRequest Request spec for updating an Nginx config.
type NginxConfigUpdateRequest struct {
	Config *NGINXaaSConfigRequest `json:"config,omitempty"`

	// Description Description of a resource.
	Description *externalRef0.NginxaasDescription `json:"description,omitempty"`
}

// NginxConfigVersion defines model for NginxConfigVersion.
type NginxConfigVersion struct {
	// Aux An array of auxiliary directory contents related to the NGINX configuration.
	Aux *[]externalRef0.DirectoryWithFileContent `json:"aux,omitempty"`

	// Checksum A hash that identifies the contents of the Nginx config version.
	Checksum NginxConfigVersionChecksum `json:"checksum"`

	// ConfPath The full path to the main NGINX configuration file. This corresponds to the `--conf-path` parameter used in the NGINX binary.
	ConfPath externalRef0.ConfigPath `json:"conf_path"`

	// ConfigVersion A hash that uniquely identifies the contents of the config object. Can be used to detect change when updating the NginxConfig.
	ConfigVersion *string `json:"config_version,omitempty"`

	// Configs An array of directories containing NGINX configuration files.
	Configs    []externalRef0.DirectoryWithFileContent `json:"configs"`
	CreatedAt  time.Time                               `json:"created_at"`
	ModifiedAt time.Time                               `json:"modified_at"`

	// ObjectId NGINX config version object id
	ObjectId externalRef0.NginxaasNginxConfigVersionObjectID `json:"object_id"`

	// OrganizationId NGINXaaS organization id
	OrganizationId externalRef0.NginxaasOrganizationID `json:"organization_id"`

	// Payloads An array of payloads that track the file paths of each SSL certificates and key, indicating where to deploy
	// them onto the data plane instance.
	// * If the `type` is `managed_certificate` or `managed_key`, you need to specify an `object_id`.
	//   * The `object_id` must represent a managed certificate object, or a `400 Bad Request` is returned.
	//   * The `contents` field is optional and is ignored if included.
	// * NGINXaaS manages deployed file paths only for managed certificates and keys. If you don't want
	// them to be managed by NGINXaaS, `inline_content` and `inline_secret` can be used for certificates or
	// keys, respectively. When you retrieve certificate deployment details, only the file paths of managed
	// certificates and keys will be shown.
	// * If you use `inline_content` and `inline_secret` in your NGINX configuration, NGINXaaS
	// will detect them. When they are used as SSL directives of the NGINX configuration
	// for certificates and keys, the certificates will be listed as `unmanaged_certificate` in the certificate
	// deployment details.
	// * if the type is `google_secret_manager` or `aws_secrets_manager`, you need to specify the secret
	// `resource_name`.
	Payloads *NGINXaaSConfigPayloads `json:"payloads,omitempty"`
}

// NginxConfigVersionChecksum A hash that identifies the contents of the Nginx config version.
type NginxConfigVersionChecksum = string

// NginxConfigVersionMeta Metadata of an Nginx config version
type NginxConfigVersionMeta struct {
	// Checksum A hash that identifies the contents of the Nginx config version.
	Checksum   NginxConfigVersionChecksum `json:"checksum"`
	CreatedAt  time.Time                  `json:"created_at"`
	ModifiedAt time.Time                  `json:"modified_at"`

	// ObjectId NGINX config version object id
	ObjectId externalRef0.NginxaasNginxConfigVersionObjectID `json:"object_id"`

	// OrganizationId NGINXaaS organization id
	OrganizationId externalRef0.NginxaasOrganizationID `json:"organization_id"`
}

// NginxConfigObjectID A globally unique identifier for the NGINX config.
type NginxConfigObjectID = externalRef0.NginxaasNginxConfigObjectID

// NginxConfigVersionID NGINX config version object id
type NginxConfigVersionID = externalRef0.NginxaasNginxConfigVersionObjectID

// CreateNginxConfigJSONRequestBody defines body for CreateNginxConfig for application/json ContentType.
type CreateNginxConfigJSONRequestBody = NginxConfigCreateRequest

// ParseNginxConfigJSONRequestBody defines body for ParseNginxConfig for application/json ContentType.
type ParseNginxConfigJSONRequestBody = NGINXaaSConfigRequest

// UpdateNginxConfigJSONRequestBody defines body for UpdateNginxConfig for application/json ContentType.
type UpdateNginxConfigJSONRequestBody = NginxConfigUpdateRequest

// ReplaceNginxConfigJSONRequestBody defines body for ReplaceNginxConfig for application/json ContentType.
type ReplaceNginxConfigJSONRequestBody = NginxConfigReplaceRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListNginxConfigs request
	ListNginxConfigs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNginxConfigWithBody request with any body
	CreateNginxConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateNginxConfig(ctx context.Context, body CreateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParseNginxConfigWithBody request with any body
	ParseNginxConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ParseNginxConfig(ctx context.Context, body ParseNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteNginxConfig request
	DeleteNginxConfig(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNginxConfig request
	GetNginxConfig(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateNginxConfigWithBody request with any body
	UpdateNginxConfigWithBody(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateNginxConfig(ctx context.Context, configId NginxConfigObjectID, body UpdateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplaceNginxConfigWithBody request with any body
	ReplaceNginxConfigWithBody(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReplaceNginxConfig(ctx context.Context, configId NginxConfigObjectID, body ReplaceNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListNginxConfigVersions request
	ListNginxConfigVersions(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteNginxConfigVersion request
	DeleteNginxConfigVersion(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConfigVersion request
	GetConfigVersion(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListNginxConfigs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNginxConfigsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNginxConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNginxConfigRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNginxConfig(ctx context.Context, body CreateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNginxConfigRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseNginxConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseNginxConfigRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseNginxConfig(ctx context.Context, body ParseNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseNginxConfigRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteNginxConfig(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteNginxConfigRequest(c.Server, configId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNginxConfig(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNginxConfigRequest(c.Server, configId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateNginxConfigWithBody(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateNginxConfigRequestWithBody(c.Server, configId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateNginxConfig(ctx context.Context, configId NginxConfigObjectID, body UpdateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateNginxConfigRequest(c.Server, configId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceNginxConfigWithBody(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceNginxConfigRequestWithBody(c.Server, configId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceNginxConfig(ctx context.Context, configId NginxConfigObjectID, body ReplaceNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceNginxConfigRequest(c.Server, configId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListNginxConfigVersions(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNginxConfigVersionsRequest(c.Server, configId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteNginxConfigVersion(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteNginxConfigVersionRequest(c.Server, configId, versionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConfigVersion(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConfigVersionRequest(c.Server, configId, versionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListNginxConfigsRequest generates requests for ListNginxConfigs
func NewListNginxConfigsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateNginxConfigRequest calls the generic CreateNginxConfig builder with application/json body
func NewCreateNginxConfigRequest(server string, body CreateNginxConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateNginxConfigRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateNginxConfigRequestWithBody generates requests for CreateNginxConfig with any type of body
func NewCreateNginxConfigRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewParseNginxConfigRequest calls the generic ParseNginxConfig builder with application/json body
func NewParseNginxConfigRequest(server string, body ParseNginxConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewParseNginxConfigRequestWithBody(server, "application/json", bodyReader)
}

// NewParseNginxConfigRequestWithBody generates requests for ParseNginxConfig with any type of body
func NewParseNginxConfigRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/parse")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteNginxConfigRequest generates requests for DeleteNginxConfig
func NewDeleteNginxConfigRequest(server string, configId NginxConfigObjectID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "config_id", configId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNginxConfigRequest generates requests for GetNginxConfig
func NewGetNginxConfigRequest(server string, configId NginxConfigObjectID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "config_id", configId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateNginxConfigRequest calls the generic UpdateNginxConfig builder with application/json body
func NewUpdateNginxConfigRequest(server string, configId NginxConfigObjectID, body UpdateNginxConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateNginxConfigRequestWithBody(server, configId, "application/json", bodyReader)
}

// NewUpdateNginxConfigRequestWithBody generates requests for UpdateNginxConfig with any type of body
func NewUpdateNginxConfigRequestWithBody(server string, configId NginxConfigObjectID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "config_id", configId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplaceNginxConfigRequest calls the generic ReplaceNginxConfig builder with application/json body
func NewReplaceNginxConfigRequest(server string, configId NginxConfigObjectID, body ReplaceNginxConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceNginxConfigRequestWithBody(server, configId, "application/json", bodyReader)
}

// NewReplaceNginxConfigRequestWithBody generates requests for ReplaceNginxConfig with any type of body
func NewReplaceNginxConfigRequestWithBody(server string, configId NginxConfigObjectID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "config_id", configId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListNginxConfigVersionsRequest generates requests for ListNginxConfigVersions
func NewListNginxConfigVersionsRequest(server string, configId NginxConfigObjectID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "config_id", configId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/%s/versions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteNginxConfigVersionRequest generates requests for DeleteNginxConfigVersion
func NewDeleteNginxConfigVersionRequest(server string, configId NginxConfigObjectID, versionId NginxConfigVersionID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "config_id", configId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version_id", versionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/%s/versions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConfigVersionRequest generates requests for GetConfigVersion
func NewGetConfigVersionRequest(server string, configId NginxConfigObjectID, versionId NginxConfigVersionID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "config_id", configId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version_id", versionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/configs/%s/versions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListNginxConfigsWithResponse request
	ListNginxConfigsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListNginxConfigsResponse, error)

	// CreateNginxConfigWithBodyWithResponse request with any body
	CreateNginxConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNginxConfigResponse, error)

	CreateNginxConfigWithResponse(ctx context.Context, body CreateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNginxConfigResponse, error)

	// ParseNginxConfigWithBodyWithResponse request with any body
	ParseNginxConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseNginxConfigResponse, error)

	ParseNginxConfigWithResponse(ctx context.Context, body ParseNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseNginxConfigResponse, error)

	// DeleteNginxConfigWithResponse request
	DeleteNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*DeleteNginxConfigResponse, error)

	// GetNginxConfigWithResponse request
	GetNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*GetNginxConfigResponse, error)

	// UpdateNginxConfigWithBodyWithResponse request with any body
	UpdateNginxConfigWithBodyWithResponse(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateNginxConfigResponse, error)

	UpdateNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, body UpdateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateNginxConfigResponse, error)

	// ReplaceNginxConfigWithBodyWithResponse request with any body
	ReplaceNginxConfigWithBodyWithResponse(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceNginxConfigResponse, error)

	ReplaceNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, body ReplaceNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceNginxConfigResponse, error)

	// ListNginxConfigVersionsWithResponse request
	ListNginxConfigVersionsWithResponse(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*ListNginxConfigVersionsResponse, error)

	// DeleteNginxConfigVersionWithResponse request
	DeleteNginxConfigVersionWithResponse(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*DeleteNginxConfigVersionResponse, error)

	// GetConfigVersionWithResponse request
	GetConfigVersionWithResponse(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*GetConfigVersionResponse, error)
}

type ListNginxConfigsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NginxConfigListResponse
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r ListNginxConfigsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNginxConfigsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListNginxConfigsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateNginxConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *NginxConfig
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r CreateNginxConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNginxConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateNginxConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ParseNginxConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.ParsedNginxConfig
	JSON400      *externalRef0.Error
	JSON401      *externalRef0.Error
	JSON500      *externalRef0.Error
}

// Status returns HTTPResponse.Status
func (r ParseNginxConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParseNginxConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ParseNginxConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteNginxConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON409      *externalRef0.Conflict
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r DeleteNginxConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteNginxConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteNginxConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetNginxConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NginxConfig
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r GetNginxConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNginxConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetNginxConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateNginxConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NginxConfig
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON409      *externalRef0.Conflict
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r UpdateNginxConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateNginxConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateNginxConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReplaceNginxConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NginxConfig
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON409      *externalRef0.Conflict
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r ReplaceNginxConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplaceNginxConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReplaceNginxConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListNginxConfigVersionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NginxConfigListVersionsResponse
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r ListNginxConfigVersionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNginxConfigVersionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListNginxConfigVersionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteNginxConfigVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON409      *externalRef0.Conflict
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r DeleteNginxConfigVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteNginxConfigVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteNginxConfigVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConfigVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NginxConfigVersion
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r GetConfigVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConfigVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConfigVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListNginxConfigsWithResponse request returning *ListNginxConfigsResponse
func (c *ClientWithResponses) ListNginxConfigsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListNginxConfigsResponse, error) {
	rsp, err := c.ListNginxConfigs(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNginxConfigsResponse(rsp)
}

// CreateNginxConfigWithBodyWithResponse request with arbitrary body returning *CreateNginxConfigResponse
func (c *ClientWithResponses) CreateNginxConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNginxConfigResponse, error) {
	rsp, err := c.CreateNginxConfigWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNginxConfigResponse(rsp)
}

func (c *ClientWithResponses) CreateNginxConfigWithResponse(ctx context.Context, body CreateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNginxConfigResponse, error) {
	rsp, err := c.CreateNginxConfig(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNginxConfigResponse(rsp)
}

// ParseNginxConfigWithBodyWithResponse request with arbitrary body returning *ParseNginxConfigResponse
func (c *ClientWithResponses) ParseNginxConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseNginxConfigResponse, error) {
	rsp, err := c.ParseNginxConfigWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseNginxConfigResponse(rsp)
}

func (c *ClientWithResponses) ParseNginxConfigWithResponse(ctx context.Context, body ParseNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseNginxConfigResponse, error) {
	rsp, err := c.ParseNginxConfig(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseNginxConfigResponse(rsp)
}

// DeleteNginxConfigWithResponse request returning *DeleteNginxConfigResponse
func (c *ClientWithResponses) DeleteNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*DeleteNginxConfigResponse, error) {
	rsp, err := c.DeleteNginxConfig(ctx, configId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteNginxConfigResponse(rsp)
}

// GetNginxConfigWithResponse request returning *GetNginxConfigResponse
func (c *ClientWithResponses) GetNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*GetNginxConfigResponse, error) {
	rsp, err := c.GetNginxConfig(ctx, configId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNginxConfigResponse(rsp)
}

// UpdateNginxConfigWithBodyWithResponse request with arbitrary body returning *UpdateNginxConfigResponse
func (c *ClientWithResponses) UpdateNginxConfigWithBodyWithResponse(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateNginxConfigResponse, error) {
	rsp, err := c.UpdateNginxConfigWithBody(ctx, configId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateNginxConfigResponse(rsp)
}

func (c *ClientWithResponses) UpdateNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, body UpdateNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateNginxConfigResponse, error) {
	rsp, err := c.UpdateNginxConfig(ctx, configId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateNginxConfigResponse(rsp)
}

// ReplaceNginxConfigWithBodyWithResponse request with arbitrary body returning *ReplaceNginxConfigResponse
func (c *ClientWithResponses) ReplaceNginxConfigWithBodyWithResponse(ctx context.Context, configId NginxConfigObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceNginxConfigResponse, error) {
	rsp, err := c.ReplaceNginxConfigWithBody(ctx, configId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceNginxConfigResponse(rsp)
}

func (c *ClientWithResponses) ReplaceNginxConfigWithResponse(ctx context.Context, configId NginxConfigObjectID, body ReplaceNginxConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceNginxConfigResponse, error) {
	rsp, err := c.ReplaceNginxConfig(ctx, configId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceNginxConfigResponse(rsp)
}

// ListNginxConfigVersionsWithResponse request returning *ListNginxConfigVersionsResponse
func (c *ClientWithResponses) ListNginxConfigVersionsWithResponse(ctx context.Context, configId NginxConfigObjectID, reqEditors ...RequestEditorFn) (*ListNginxConfigVersionsResponse, error) {
	rsp, err := c.ListNginxConfigVersions(ctx, configId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNginxConfigVersionsResponse(rsp)
}

// DeleteNginxConfigVersionWithResponse request returning *DeleteNginxConfigVersionResponse
func (c *ClientWithResponses) DeleteNginxConfigVersionWithResponse(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*DeleteNginxConfigVersionResponse, error) {
	rsp, err := c.DeleteNginxConfigVersion(ctx, configId, versionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteNginxConfigVersionResponse(rsp)
}

// GetConfigVersionWithResponse request returning *GetConfigVersionResponse
func (c *ClientWithResponses) GetConfigVersionWithResponse(ctx context.Context, configId NginxConfigObjectID, versionId NginxConfigVersionID, reqEditors ...RequestEditorFn) (*GetConfigVersionResponse, error) {
	rsp, err := c.GetConfigVersion(ctx, configId, versionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConfigVersionResponse(rsp)
}

// ParseListNginxConfigsResponse parses an HTTP response from a ListNginxConfigsWithResponse call
func ParseListNginxConfigsResponse(rsp *http.Response) (*ListNginxConfigsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNginxConfigsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NginxConfigListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateNginxConfigResponse parses an HTTP response from a CreateNginxConfigWithResponse call
func ParseCreateNginxConfigResponse(rsp *http.Response) (*CreateNginxConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNginxConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest NginxConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseParseNginxConfigResponse parses an HTTP response from a ParseNginxConfigWithResponse call
func ParseParseNginxConfigResponse(rsp *http.Response) (*ParseNginxConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParseNginxConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.ParsedNginxConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteNginxConfigResponse parses an HTTP response from a DeleteNginxConfigWithResponse call
func ParseDeleteNginxConfigResponse(rsp *http.Response) (*DeleteNginxConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteNginxConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetNginxConfigResponse parses an HTTP response from a GetNginxConfigWithResponse call
func ParseGetNginxConfigResponse(rsp *http.Response) (*GetNginxConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNginxConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NginxConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateNginxConfigResponse parses an HTTP response from a UpdateNginxConfigWithResponse call
func ParseUpdateNginxConfigResponse(rsp *http.Response) (*UpdateNginxConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateNginxConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NginxConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseReplaceNginxConfigResponse parses an HTTP response from a ReplaceNginxConfigWithResponse call
func ParseReplaceNginxConfigResponse(rsp *http.Response) (*ReplaceNginxConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplaceNginxConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NginxConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListNginxConfigVersionsResponse parses an HTTP response from a ListNginxConfigVersionsWithResponse call
func ParseListNginxConfigVersionsResponse(rsp *http.Response) (*ListNginxConfigVersionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNginxConfigVersionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NginxConfigListVersionsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteNginxConfigVersionResponse parses an HTTP response from a DeleteNginxConfigVersionWithResponse call
func ParseDeleteNginxConfigVersionResponse(rsp *http.Response) (*DeleteNginxConfigVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteNginxConfigVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetConfigVersionResponse parses an HTTP response from a GetConfigVersionWithResponse call
func ParseGetConfigVersionResponse(rsp *http.Response) (*GetConfigVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConfigVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NginxConfigVersion
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
