// Package v20260731 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v20260731

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"

	externalRef0 "github.com/F5Networks/terraform-provider-f5ads/internal/provider/clients/naas"
)

type CertificateStatus = externalRef0.CertificateStatus
type NginxConfigPayloads = externalRef0.NginxConfigPayloads
type ConfigPath = externalRef0.ConfigPath
type FileDataRequest = externalRef0.FileDataRequest
type DirectoryRequestWithFileContent = externalRef0.DirectoryRequestWithFileContent
type DirectoryWithFileContent = externalRef0.DirectoryWithFileContent

// Defines values for CertificateAssociationType.
const (
	ReferenceTypeDeployment  CertificateAssociationType = "deployment"
	ReferenceTypeNginxConfig CertificateAssociationType = "nginx_config"
)

// Valid indicates whether the value is a known member of the CertificateAssociationType enum.
func (e CertificateAssociationType) Valid() bool {
	switch e {
	case ReferenceTypeDeployment:
		return true
	case ReferenceTypeNginxConfig:
		return true
	default:
		return false
	}
}

// Defines values for CertificateType.
const (
	CertificateTypeAwsSecret    CertificateType = "aws_secret"
	CertificateTypeCaBundle     CertificateType = "ca_bundle"
	CertificateTypeGoogleSecret CertificateType = "google_secret"
	CertificateTypePemCertKey   CertificateType = "cert_key"
)

// Valid indicates whether the value is a known member of the CertificateType enum.
func (e CertificateType) Valid() bool {
	switch e {
	case CertificateTypeAwsSecret:
		return true
	case CertificateTypeCaBundle:
		return true
	case CertificateTypeGoogleSecret:
		return true
	case CertificateTypePemCertKey:
		return true
	default:
		return false
	}
}

// Defines values for FilterNameCertificates.
const (
	FilterNameCertificatesName        FilterNameCertificates = "name"
	FilterNameCertificatesObjectId    FilterNameCertificates = "object_id"
	FilterNameCertificatesStatus      FilterNameCertificates = "status"
	FilterNameCertificatesSubjectName FilterNameCertificates = "subject_name"
	FilterNameCertificatesType        FilterNameCertificates = "type"
)

// Valid indicates whether the value is a known member of the FilterNameCertificates enum.
func (e FilterNameCertificates) Valid() bool {
	switch e {
	case FilterNameCertificatesName:
		return true
	case FilterNameCertificatesObjectId:
		return true
	case FilterNameCertificatesStatus:
		return true
	case FilterNameCertificatesSubjectName:
		return true
	case FilterNameCertificatesType:
		return true
	default:
		return false
	}
}

// Defines values for ListCertificatesParamsSortDir.
const (
	ListCertificatesParamsSortDirAscending  ListCertificatesParamsSortDir = "Ascending"
	ListCertificatesParamsSortDirDescending ListCertificatesParamsSortDir = "Descending"
)

// Valid indicates whether the value is a known member of the ListCertificatesParamsSortDir enum.
func (e ListCertificatesParamsSortDir) Valid() bool {
	switch e {
	case ListCertificatesParamsSortDirAscending:
		return true
	case ListCertificatesParamsSortDirDescending:
		return true
	default:
		return false
	}
}

// Defines values for ListCertificatesParamsSortFields.
const (
	SortNameCertificatesName        ListCertificatesParamsSortFields = "name"
	SortNameCertificatesNotAfter    ListCertificatesParamsSortFields = "not_after"
	SortNameCertificatesNotBefore   ListCertificatesParamsSortFields = "not_before"
	SortNameCertificatesSubjectName ListCertificatesParamsSortFields = "subject_name"
)

// Valid indicates whether the value is a known member of the ListCertificatesParamsSortFields enum.
func (e ListCertificatesParamsSortFields) Valid() bool {
	switch e {
	case SortNameCertificatesName:
		return true
	case SortNameCertificatesNotAfter:
		return true
	case SortNameCertificatesNotBefore:
		return true
	case SortNameCertificatesSubjectName:
		return true
	default:
		return false
	}
}

// Defines values for ListCertificateReferencesParamsSortDir.
const (
	ListCertificateReferencesParamsSortDirAscending  ListCertificateReferencesParamsSortDir = "Ascending"
	ListCertificateReferencesParamsSortDirDescending ListCertificateReferencesParamsSortDir = "Descending"
)

// Valid indicates whether the value is a known member of the ListCertificateReferencesParamsSortDir enum.
func (e ListCertificateReferencesParamsSortDir) Valid() bool {
	switch e {
	case ListCertificateReferencesParamsSortDirAscending:
		return true
	case ListCertificateReferencesParamsSortDirDescending:
		return true
	default:
		return false
	}
}

// Defines values for ListCertificateReferencesParamsSortFields.
const (
	SortNameCertificateDeploymentsName ListCertificateReferencesParamsSortFields = "name"
)

// Valid indicates whether the value is a known member of the ListCertificateReferencesParamsSortFields enum.
func (e ListCertificateReferencesParamsSortFields) Valid() bool {
	switch e {
	case SortNameCertificateDeploymentsName:
		return true
	default:
		return false
	}
}

// CertificateAssociationDeployment A certificate reference from a deployment
type CertificateAssociationDeployment struct {
	// AssociationType The type of the association
	AssociationType CertificateAssociationType `json:"association_type"`

	// CertPaths Deployment file paths for public certificates.
	CertPaths *[]string `json:"cert_paths,omitempty"`

	// DeploymentId A globally unique identifier for the deployment.
	DeploymentId externalRef0.DeploymentObjectID `json:"deployment_id"`

	// KeyPaths Deployment file paths for the private key.
	KeyPaths *[]string `json:"key_paths,omitempty"`
}

// CertificateAssociationNginxConfig A certificate reference from a deployment
type CertificateAssociationNginxConfig struct {
	// AssociationType The type of the association
	AssociationType CertificateAssociationType `json:"association_type"`

	// CertPaths Deployment file paths for public certificates.
	CertPaths *[]string `json:"cert_paths,omitempty"`

	// ConfigId A globally unique identifier for the NGINX config.
	ConfigId externalRef0.NginxaasNginxConfigObjectID `json:"config_id"`

	// ConfigVersionId NGINX config version object id
	ConfigVersionId externalRef0.NginxaasNginxConfigVersionObjectID `json:"config_version_id"`

	// KeyPaths Deployment file paths for the private key.
	KeyPaths *[]string `json:"key_paths,omitempty"`
}

// CertificateAssociationType The type of the association
type CertificateAssociationType string

// CertificateCreateRequest Request structure for creating a certificate with an optional private key. Unlike the shared CertificateRequest used by the parse endpoint, a name is required here because the certificate is persisted.
type CertificateCreateRequest struct {
	// Content Defines the PEM-formatted certificate content which includes the certificates and corresponding private key, all encoded in base64.
	Content externalRef0.CertificateContent `json:"content"`

	// Name A name for the certificate, making it identifiable among others.
	Name string `json:"name"`
}

// CertificateDisplayMetadata This represents the essential metadata of a public certificate.
type CertificateDisplayMetadata = externalRef0.CertificateDisplayMetadata

// CertificateListResponse defines model for CertificateListResponse.
type CertificateListResponse struct {
	// Count The total number of results generated by the list or query operation, accounting for any filter(s).
	// This number can be greater than the number of returned resources when pagination is in effect and a page size limit (or maximum allowed) is reached.
	Count int `json:"count"`

	// Items An array of basic metadata for all the SSL certificates in NGINXaaS.
	// For a CA bundle, an overview with metadata on the first Certificate Authority in the bundle will be displayed.
	// Otherwise, an overview with metadata on the leaf certificate will be displayed.
	Items []CertificateOverviewMetadata `json:"items"`

	// ItemsPerPage The number of items to display per page. This is disregarded when `paginated=false`.
	ItemsPerPage *int `json:"items_per_page,omitempty"`

	// StartIndex The first result's starting position in the list. This is disregarded when `paginated=false`.
	StartIndex *int `json:"start_index,omitempty"`

	// Total The absolute total number of the resource in the NGINX One Console, ignoring any filter(s).
	Total int `json:"total"`
}

// CertificateMetadata A comprehensive list of all the metadata for a public certificate.
type CertificateMetadata struct {
	// AuthorityKeyIdentifier The identifier of the signing authority for the certificate.
	AuthorityKeyIdentifier *string `json:"authority_key_identifier,omitempty"`

	// CommonName The Common Name (CN) for the certificate, used when DNS name is not present in the SAN extension.
	CommonName *string `json:"common_name,omitempty"`

	// Issuer Identifies the entity who signed and issued the certificate.
	Issuer *string `json:"issuer,omitempty"`

	// NotAfter The end of the validity period for the certificate.
	NotAfter time.Time `json:"not_after"`

	// NotBefore The start of the validity period for the certificate.
	NotBefore time.Time `json:"not_before"`

	// PublicKeyType Identifies the encryption algorithm used to create the public key for the certificate.
	PublicKeyType string `json:"public_key_type"`

	// SerialNumber Certificate serial number
	SerialNumber string `json:"serial_number"`

	// SignatureAlgorithm Identifies the algorithm used to sign the certificate.
	SignatureAlgorithm string `json:"signature_algorithm"`

	// Status Status of the certificate:
	//   * `valid` - The certificate is currently valid and operational.
	//   * `expiring` -  The certificate will expire within the next 30 days. Consider renewing it to maintain uninterrupted service.
	//   * `expired` - The certificate is no longer valid. Immediate renewal is recommended to ensure secure connections.
	//   * `not_ready` - The certificate is not ready to be used, based on the start date of its validity period.
	Status externalRef0.CertificateStatus `json:"status"`

	// Subject Identifies the primary entity to which the certificate is issued. Typically, it contains information
	// such as the Common Name (CN), Organization (O), Organizational Unit (OU), Country (C), etc.
	Subject *string `json:"subject,omitempty"`

	// SubjectAlternativeName Defines additional identifies bound to the subject of the certificate.
	// For example, the DNS name is used to add additional domain names to a certificate.
	SubjectAlternativeName *[]string `json:"subject_alternative_name,omitempty"`

	// SubjectKeyIdentifier A hash value of the SSL certificate that can be used to identify certificates that
	// contain a particular public key.
	SubjectKeyIdentifier *string `json:"subject_key_identifier,omitempty"`

	// Thumbprint A hash to ensure that the certificate has not been modified.
	Thumbprint string `json:"thumbprint"`

	// ThumbprintAlgorithm Defines the algorithm used to hash the certificate.
	ThumbprintAlgorithm *string `json:"thumbprint_algorithm,omitempty"`
}

// CertificateObjectMetadata defines model for CertificateObjectMetadata.
type CertificateObjectMetadata struct {
	// CertsCount The number of public certificates under this certificate object.
	CertsCount int64 `json:"certs_count"`

	// Name Name of the certificate, optionally specified upon creation
	Name string `json:"name"`

	// ObjectId A globally unique identifier for the certificates.
	ObjectId externalRef0.CertificateObjectID `json:"object_id"`

	// ResourceName The resource name of the certificate from an external resource (e.g., Google Secret Manager).
	ResourceName *string `json:"resource_name,omitempty"`

	// Type Certificate type:
	//   * `ca_bundle` - This certificate object is a CA bundle.
	//   * `cert_key` - This certificate object is consisted of public certificates and key.
	//   * `google_secret` - This certificate is fetched from Google Secret Manager.
	//   * `aws_secret` - This certificate is fetched from AWS Secrets Manager.
	Type CertificateType `json:"type"`
}

// CertificateOverviewMetadata defines model for CertificateOverviewMetadata.
type CertificateOverviewMetadata struct {
	// CertsCount The number of public certificates under this certificate object.
	CertsCount int64 `json:"certs_count"`

	// Name Name of the certificate, optionally specified upon creation
	Name string `json:"name"`

	// NotAfter The end of the validity period for the certificate.
	NotAfter time.Time `json:"not_after"`

	// NotBefore The start of the validity period for the certificate.
	NotBefore time.Time `json:"not_before"`

	// ObjectId A globally unique identifier for the certificates.
	ObjectId externalRef0.CertificateObjectID `json:"object_id"`

	// ResourceName The resource name of the certificate from an external resource (e.g., Google Secret Manager).
	ResourceName *string `json:"resource_name,omitempty"`

	// Status Status of the certificate:
	//   * `valid` - The certificate is currently valid and operational.
	//   * `expiring` -  The certificate will expire within the next 30 days. Consider renewing it to maintain uninterrupted service.
	//   * `expired` - The certificate is no longer valid. Immediate renewal is recommended to ensure secure connections.
	//   * `not_ready` - The certificate is not ready to be used, based on the start date of its validity period.
	Status CertificateStatus `json:"status"`

	// SubjectName DNS name that identifies the certificate. If DNS is not present in the SAN extension, this will be the common name.
	SubjectName string `json:"subject_name"`

	// Type Certificate type:
	//   * `ca_bundle` - This certificate object is a CA bundle.
	//   * `cert_key` - This certificate object is consisted of public certificates and key.
	//   * `google_secret` - This certificate is fetched from Google Secret Manager.
	//   * `aws_secret` - This certificate is fetched from AWS Secrets Manager.
	Type CertificateType `json:"type"`
}

// CertificateParseResponse defines model for CertificateParseResponse.
type CertificateParseResponse struct {
	// Key Metadata for a private key.
	Key *externalRef0.PrivateKeyMetadata `json:"key,omitempty"`

	// NotAfter The end of the validity period for the certificate.
	NotAfter time.Time `json:"not_after"`

	// NotBefore The start of the validity period for the certificate.
	NotBefore time.Time `json:"not_before"`

	// Status Status of the certificate:
	//   * `valid` - The certificate is currently valid and operational.
	//   * `expiring` -  The certificate will expire within the next 30 days. Consider renewing it to maintain uninterrupted service.
	//   * `expired` - The certificate is no longer valid. Immediate renewal is recommended to ensure secure connections.
	//   * `not_ready` - The certificate is not ready to be used, based on the start date of its validity period.
	Status CertificateStatus `json:"status"`

	// SubjectName DNS name that identifies the certificate. If DNS is not present in the SAN extension, this will be the common name.
	SubjectName string `json:"subject_name"`

	// Type Certificate type:
	//   * `ca_bundle` - This certificate object is a CA bundle.
	//   * `cert_key` - This certificate object is consisted of public certificates and key.
	//   * `google_secret` - This certificate is fetched from Google Secret Manager.
	//   * `aws_secret` - This certificate is fetched from AWS Secrets Manager.
	Type *CertificateType `json:"type,omitempty"`

	// Warnings Warnings indicate whether there are any issues with the stored cert object. Only present when issues were found.
	Warnings *string `json:"warnings,omitempty"`
}

// CertificateReference Response structure containing certificate reference details for an SSL certificate
type CertificateReference struct {
	union json.RawMessage
}

// CertificateReferenceListResponse defines model for CertificateReferenceListResponse.
type CertificateReferenceListResponse struct {
	// Count The total number of results generated by the list or query operation, accounting for any filter(s).
	// This number can be greater than the number of returned resources when pagination is in effect and a page size limit (or maximum allowed) is reached.
	Count int `json:"count"`

	// Items An array of certificate references for an SSL certificate. If this certificate object represents a
	// CA bundle, there will be only public certificate file paths in the certificate deployment details.
	Items []CertificateReference `json:"items"`

	// ItemsPerPage The number of items to display per page. This is disregarded when `paginated=false`.
	ItemsPerPage *int `json:"items_per_page,omitempty"`

	// StartIndex The first result's starting position in the list. This is disregarded when `paginated=false`.
	StartIndex *int `json:"start_index,omitempty"`

	// Total The absolute total number of the resource in the NGINX One Console, ignoring any filter(s).
	Total int `json:"total"`
}

// CertificateResponse defines model for CertificateResponse.
type CertificateResponse struct {
	// Certs An array of metadata for all the public certificates under the cert object.
	Certs *[]CertificateMetadata `json:"certs,omitempty"`

	// CertsCount The number of public certificates under this certificate object.
	CertsCount int64 `json:"certs_count"`

	// CreatedAt The date and time when the SSL certificate was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Key Metadata for a private key.
	Key *externalRef0.PrivateKeyMetadata `json:"key,omitempty"`

	// ModifiedAt The date and time when the SSL certificate was last modified.
	ModifiedAt *time.Time `json:"modified_at,omitempty"`

	// Name Name of the certificate, optionally specified upon creation
	Name string `json:"name"`

	// NotAfter The end of the validity period for the certificate.
	NotAfter time.Time `json:"not_after"`

	// NotBefore The start of the validity period for the certificate.
	NotBefore time.Time `json:"not_before"`

	// ObjectId A globally unique identifier for the certificates.
	ObjectId externalRef0.CertificateObjectID `json:"object_id"`

	// ResourceName The resource name of the certificate from an external resource (e.g., Google Secret Manager).
	ResourceName *string `json:"resource_name,omitempty"`

	// Status Status of the certificate:
	//   * `valid` - The certificate is currently valid and operational.
	//   * `expiring` -  The certificate will expire within the next 30 days. Consider renewing it to maintain uninterrupted service.
	//   * `expired` - The certificate is no longer valid. Immediate renewal is recommended to ensure secure connections.
	//   * `not_ready` - The certificate is not ready to be used, based on the start date of its validity period.
	Status CertificateStatus `json:"status"`

	// SubjectName DNS name that identifies the certificate. If DNS is not present in the SAN extension, this will be the common name.
	SubjectName string `json:"subject_name"`

	// Type Certificate type:
	//   * `ca_bundle` - This certificate object is a CA bundle.
	//   * `cert_key` - This certificate object is consisted of public certificates and key.
	//   * `google_secret` - This certificate is fetched from Google Secret Manager.
	//   * `aws_secret` - This certificate is fetched from AWS Secrets Manager.
	Type CertificateType `json:"type"`

	// Warnings Warnings indicate whether there are any issues with the stored cert object. Empty when no issues were found.
	Warnings *string `json:"warnings,omitempty"`
}

// CertificateType Certificate type:
//   - `ca_bundle` - This certificate object is a CA bundle.
//   - `cert_key` - This certificate object is consisted of public certificates and key.
//   - `google_secret` - This certificate is fetched from Google Secret Manager.
//   - `aws_secret` - This certificate is fetched from AWS Secrets Manager.
type CertificateType string

// FilterNameCertificates Keywords for certificates filters.
// When filtering on `type`, only the following `filter_values` are supported:
//   - cert_key
//   - ca_bundle
//   - unknown
//
// When filtering on `status`, only the following `filter_values` are supported:
//   - valid
//   - expiring
//   - expired
//   - not_ready
type FilterNameCertificates string

// FilterFieldCertificates defines model for FilterFieldCertificates.
type FilterFieldCertificates = []FilterNameCertificates

// ListCertificatesParams defines parameters for ListCertificates.
type ListCertificatesParams struct {
	// Paginated A boolean indicating if the results should be presented as a paginated list. Defaults to `true`.
	// When set to `false` a maximum of 3000 results are returned.
	Paginated *externalRef0.Paginated `form:"paginated,omitempty" json:"paginated,omitempty"`

	// Limit An integer that specifies the maximum number of items to be returned.
	// Setting this to `0` will result in no items being returned, but a total count will still be provided.
	// This parameter is not applicable if `paginated` is `false`.
	Limit *externalRef0.Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset An integer that specifies the starting position of the results, starting at `1`.
	// This parameter is not applicable if `paginated` is `false`.
	Offset *externalRef0.Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// FilterFields Filter options for certificates; used in conjunction with other filter parameters having the same array length.
	FilterFields *FilterFieldCertificates `form:"filter_fields,omitempty" json:"filter_fields,omitempty"`

	// FilterOps An array of strings defining the operands for filtering, to be used in conjunction with `filter_fields` and `filter_values`.
	// All filter parameters must have matching array lengths. Currently, the only supported operand is `"IN"`.
	FilterOps *externalRef0.FilterOperands `form:"filter_ops,omitempty" json:"filter_ops,omitempty"`

	// FilterValues An array of strings containing the keywords for filtering.
	// Multiple keywords can be chained using the `|` character.
	// Ensure this parameter's array length matches those of `filter_fields` and `filter_ops` for effective filtering.
	// The total length of the filter string should not exceed 1024 characters.
	FilterValues *externalRef0.FilterValues `form:"filter_values,omitempty" json:"filter_values,omitempty"`

	// SortDir Sorting direction for the criteria and the resulting collection returned. Defaults to descending if not specified.
	SortDir *ListCertificatesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// SortFields Sort certificates by enumerate value(s). Ordinal position determines primary, secondary, etc.
	SortFields *externalRef0.SortNameCertificates `form:"sort_fields,omitempty" json:"sort_fields,omitempty"`
}

// ListCertificatesParamsSortDir defines parameters for ListCertificates.
type ListCertificatesParamsSortDir string

// ListCertificatesParamsSortFields defines parameters for ListCertificates.
type ListCertificatesParamsSortFields string

// ListCertificateReferencesParams defines parameters for ListCertificateReferences.
type ListCertificateReferencesParams struct {
	// Paginated A boolean indicating if the results should be presented as a paginated list. Defaults to `true`.
	// When set to `false` a maximum of 3000 results are returned.
	Paginated *externalRef0.Paginated `form:"paginated,omitempty" json:"paginated,omitempty"`

	// Limit An integer that specifies the maximum number of items to be returned.
	// Setting this to `0` will result in no items being returned, but a total count will still be provided.
	// This parameter is not applicable if `paginated` is `false`.
	Limit *externalRef0.Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset An integer that specifies the starting position of the results, starting at `1`.
	// This parameter is not applicable if `paginated` is `false`.
	Offset *externalRef0.Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// FilterFields Filter options for certificate deployments; used in conjunction with other filter parameters having the same array length.
	FilterFields *externalRef0.FilterFieldCertificateDeployments `form:"filter_fields,omitempty" json:"filter_fields,omitempty"`

	// FilterOps An array of strings defining the operands for filtering, to be used in conjunction with `filter_fields` and `filter_values`.
	// All filter parameters must have matching array lengths. Currently, the only supported operand is `"IN"`.
	FilterOps *externalRef0.FilterOperands `form:"filter_ops,omitempty" json:"filter_ops,omitempty"`

	// FilterValues An array of strings containing the keywords for filtering.
	// Multiple keywords can be chained using the `|` character.
	// Ensure this parameter's array length matches those of `filter_fields` and `filter_ops` for effective filtering.
	// The total length of the filter string should not exceed 1024 characters.
	FilterValues *externalRef0.FilterValues `form:"filter_values,omitempty" json:"filter_values,omitempty"`

	// SortDir Sorting direction for the criteria and the resulting collection returned. Defaults to descending if not specified.
	SortDir *ListCertificateReferencesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// SortFields Sort certificate deployments by enumerate value(s). Ordinal position determines primary, secondary, etc.
	SortFields *externalRef0.SortNameCertificateDeployments `form:"sort_fields,omitempty" json:"sort_fields,omitempty"`
}

// ListCertificateReferencesParamsSortDir defines parameters for ListCertificateReferences.
type ListCertificateReferencesParamsSortDir string

// ListCertificateReferencesParamsSortFields defines parameters for ListCertificateReferences.
type ListCertificateReferencesParamsSortFields string

// CreateCertificateJSONRequestBody defines body for CreateCertificate for application/json ContentType.
type CreateCertificateJSONRequestBody = CertificateCreateRequest

// ParseCertificateJSONRequestBody defines body for ParseCertificate for application/json ContentType.
type ParseCertificateJSONRequestBody = externalRef0.CertificateRequest

// AsCertificateAssociationDeployment returns the union data inside the CertificateReference as a CertificateAssociationDeployment
func (t CertificateReference) AsCertificateAssociationDeployment() (CertificateAssociationDeployment, error) {
	var body CertificateAssociationDeployment
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCertificateAssociationDeployment overwrites any union data inside the CertificateReference as the provided CertificateAssociationDeployment
func (t *CertificateReference) FromCertificateAssociationDeployment(v CertificateAssociationDeployment) error {
	v.AssociationType = "deployment"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCertificateAssociationDeployment performs a merge with any union data inside the CertificateReference, using the provided CertificateAssociationDeployment
func (t *CertificateReference) MergeCertificateAssociationDeployment(v CertificateAssociationDeployment) error {
	v.AssociationType = "deployment"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCertificateAssociationNginxConfig returns the union data inside the CertificateReference as a CertificateAssociationNginxConfig
func (t CertificateReference) AsCertificateAssociationNginxConfig() (CertificateAssociationNginxConfig, error) {
	var body CertificateAssociationNginxConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCertificateAssociationNginxConfig overwrites any union data inside the CertificateReference as the provided CertificateAssociationNginxConfig
func (t *CertificateReference) FromCertificateAssociationNginxConfig(v CertificateAssociationNginxConfig) error {
	v.AssociationType = "nginx_config"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCertificateAssociationNginxConfig performs a merge with any union data inside the CertificateReference, using the provided CertificateAssociationNginxConfig
func (t *CertificateReference) MergeCertificateAssociationNginxConfig(v CertificateAssociationNginxConfig) error {
	v.AssociationType = "nginx_config"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CertificateReference) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"association_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CertificateReference) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "deployment":
		return t.AsCertificateAssociationDeployment()
	case "nginx_config":
		return t.AsCertificateAssociationNginxConfig()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CertificateReference) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CertificateReference) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListCertificates request
	ListCertificates(ctx context.Context, params *ListCertificatesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCertificateWithBody request with any body
	CreateCertificateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCertificate(ctx context.Context, body CreateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParseCertificateWithBody request with any body
	ParseCertificateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ParseCertificate(ctx context.Context, body ParseCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCertificate request
	DeleteCertificate(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCertificate request
	GetCertificate(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCertificateReferences request
	ListCertificateReferences(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, params *ListCertificateReferencesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListCertificates(ctx context.Context, params *ListCertificatesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCertificatesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCertificateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCertificateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCertificate(ctx context.Context, body CreateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCertificateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseCertificateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseCertificateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseCertificate(ctx context.Context, body ParseCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseCertificateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteCertificate(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCertificateRequest(c.Server, certificateObjectID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCertificate(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCertificateRequest(c.Server, certificateObjectID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCertificateReferences(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, params *ListCertificateReferencesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCertificateReferencesRequest(c.Server, certificateObjectID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListCertificatesRequest generates requests for ListCertificates
func NewListCertificatesRequest(server string, params *ListCertificatesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/certificates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Paginated != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "paginated", *params.Paginated, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterFields != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter_fields", *params.FilterFields, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterOps != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter_ops", *params.FilterOps, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterValues != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter_values", *params.FilterValues, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortDir != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_dir", *params.SortDir, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortFields != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_fields", *params.SortFields, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCertificateRequest calls the generic CreateCertificate builder with application/json body
func NewCreateCertificateRequest(server string, body CreateCertificateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCertificateRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCertificateRequestWithBody generates requests for CreateCertificate with any type of body
func NewCreateCertificateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/certificates")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewParseCertificateRequest calls the generic ParseCertificate builder with application/json body
func NewParseCertificateRequest(server string, body ParseCertificateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewParseCertificateRequestWithBody(server, "application/json", bodyReader)
}

// NewParseCertificateRequestWithBody generates requests for ParseCertificate with any type of body
func NewParseCertificateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/certificates/parse")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCertificateRequest generates requests for DeleteCertificate
func NewDeleteCertificateRequest(server string, certificateObjectID externalRef0.CertificateParamObjectID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "certificateObjectID", certificateObjectID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/certificates/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCertificateRequest generates requests for GetCertificate
func NewGetCertificateRequest(server string, certificateObjectID externalRef0.CertificateParamObjectID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "certificateObjectID", certificateObjectID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/certificates/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCertificateReferencesRequest generates requests for ListCertificateReferences
func NewListCertificateReferencesRequest(server string, certificateObjectID externalRef0.CertificateParamObjectID, params *ListCertificateReferencesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "certificateObjectID", certificateObjectID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/certificates/%s/references", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Paginated != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "paginated", *params.Paginated, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterFields != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter_fields", *params.FilterFields, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterOps != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter_ops", *params.FilterOps, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.FilterValues != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter_values", *params.FilterValues, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortDir != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_dir", *params.SortDir, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SortFields != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_fields", *params.SortFields, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListCertificatesWithResponse request
	ListCertificatesWithResponse(ctx context.Context, params *ListCertificatesParams, reqEditors ...RequestEditorFn) (*ListCertificatesResponse, error)

	// CreateCertificateWithBodyWithResponse request with any body
	CreateCertificateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCertificateResponse, error)

	CreateCertificateWithResponse(ctx context.Context, body CreateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCertificateResponse, error)

	// ParseCertificateWithBodyWithResponse request with any body
	ParseCertificateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseCertificateResponse, error)

	ParseCertificateWithResponse(ctx context.Context, body ParseCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseCertificateResponse, error)

	// DeleteCertificateWithResponse request
	DeleteCertificateWithResponse(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*DeleteCertificateResponse, error)

	// GetCertificateWithResponse request
	GetCertificateWithResponse(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*GetCertificateResponse, error)

	// ListCertificateReferencesWithResponse request
	ListCertificateReferencesWithResponse(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, params *ListCertificateReferencesParams, reqEditors ...RequestEditorFn) (*ListCertificateReferencesResponse, error)
}

type ListCertificatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateListResponse
	JSON401      *externalRef0.Error
	JSON500      *externalRef0.Error
}

// Status returns HTTPResponse.Status
func (r ListCertificatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCertificatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCertificatesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateResponse
	JSON400      *externalRef0.Error
	JSON401      *externalRef0.Error
	JSON500      *externalRef0.Error
}

// Status returns HTTPResponse.Status
func (r CreateCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ParseCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateParseResponse
	JSON400      *externalRef0.Error
	JSON401      *externalRef0.Error
	JSON500      *externalRef0.Error
}

// Status returns HTTPResponse.Status
func (r ParseCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParseCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ParseCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *externalRef0.Error
	JSON401      *externalRef0.Error
	JSON404      *externalRef0.Error
	JSON409      *externalRef0.Error
	JSON500      *externalRef0.Error
}

// Status returns HTTPResponse.Status
func (r DeleteCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateResponse
	JSON401      *externalRef0.Error
	JSON404      *externalRef0.Error
	JSON500      *externalRef0.Error
}

// Status returns HTTPResponse.Status
func (r GetCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListCertificateReferencesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateReferenceListResponse
	JSON401      *externalRef0.Error
	JSON404      *externalRef0.Error
	JSON500      *externalRef0.Error
}

// Status returns HTTPResponse.Status
func (r ListCertificateReferencesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCertificateReferencesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCertificateReferencesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListCertificatesWithResponse request returning *ListCertificatesResponse
func (c *ClientWithResponses) ListCertificatesWithResponse(ctx context.Context, params *ListCertificatesParams, reqEditors ...RequestEditorFn) (*ListCertificatesResponse, error) {
	rsp, err := c.ListCertificates(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCertificatesResponse(rsp)
}

// CreateCertificateWithBodyWithResponse request with arbitrary body returning *CreateCertificateResponse
func (c *ClientWithResponses) CreateCertificateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCertificateResponse, error) {
	rsp, err := c.CreateCertificateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCertificateResponse(rsp)
}

func (c *ClientWithResponses) CreateCertificateWithResponse(ctx context.Context, body CreateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCertificateResponse, error) {
	rsp, err := c.CreateCertificate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCertificateResponse(rsp)
}

// ParseCertificateWithBodyWithResponse request with arbitrary body returning *ParseCertificateResponse
func (c *ClientWithResponses) ParseCertificateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseCertificateResponse, error) {
	rsp, err := c.ParseCertificateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseCertificateResponse(rsp)
}

func (c *ClientWithResponses) ParseCertificateWithResponse(ctx context.Context, body ParseCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseCertificateResponse, error) {
	rsp, err := c.ParseCertificate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseCertificateResponse(rsp)
}

// DeleteCertificateWithResponse request returning *DeleteCertificateResponse
func (c *ClientWithResponses) DeleteCertificateWithResponse(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*DeleteCertificateResponse, error) {
	rsp, err := c.DeleteCertificate(ctx, certificateObjectID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteCertificateResponse(rsp)
}

// GetCertificateWithResponse request returning *GetCertificateResponse
func (c *ClientWithResponses) GetCertificateWithResponse(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, reqEditors ...RequestEditorFn) (*GetCertificateResponse, error) {
	rsp, err := c.GetCertificate(ctx, certificateObjectID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCertificateResponse(rsp)
}

// ListCertificateReferencesWithResponse request returning *ListCertificateReferencesResponse
func (c *ClientWithResponses) ListCertificateReferencesWithResponse(ctx context.Context, certificateObjectID externalRef0.CertificateParamObjectID, params *ListCertificateReferencesParams, reqEditors ...RequestEditorFn) (*ListCertificateReferencesResponse, error) {
	rsp, err := c.ListCertificateReferences(ctx, certificateObjectID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCertificateReferencesResponse(rsp)
}

// ParseListCertificatesResponse parses an HTTP response from a ListCertificatesWithResponse call
func ParseListCertificatesResponse(rsp *http.Response) (*ListCertificatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCertificatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateCertificateResponse parses an HTTP response from a CreateCertificateWithResponse call
func ParseCreateCertificateResponse(rsp *http.Response) (*CreateCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseParseCertificateResponse parses an HTTP response from a ParseCertificateWithResponse call
func ParseParseCertificateResponse(rsp *http.Response) (*ParseCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParseCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateParseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteCertificateResponse parses an HTTP response from a DeleteCertificateWithResponse call
func ParseDeleteCertificateResponse(rsp *http.Response) (*DeleteCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetCertificateResponse parses an HTTP response from a GetCertificateWithResponse call
func ParseGetCertificateResponse(rsp *http.Response) (*GetCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListCertificateReferencesResponse parses an HTTP response from a ListCertificateReferencesWithResponse call
func ParseListCertificateReferencesResponse(rsp *http.Response) (*ListCertificateReferencesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCertificateReferencesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateReferenceListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
