// Package v20260731 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v20260731

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"

	externalRef0 "github.com/F5Networks/terraform-provider-f5ads/internal/provider/clients/naas"
)

// Defines values for DeploymentCloudName.
const (
	Aws    DeploymentCloudName = "aws"
	Azure  DeploymentCloudName = "azure"
	Google DeploymentCloudName = "google"
)

// Valid indicates whether the value is a known member of the DeploymentCloudName enum.
func (e DeploymentCloudName) Valid() bool {
	switch e {
	case Aws:
		return true
	case Azure:
		return true
	case Google:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStateState.
const (
	Deleting  DeploymentStateState = "deleting"
	Failed    DeploymentStateState = "failed"
	Pending   DeploymentStateState = "pending"
	Ready     DeploymentStateState = "ready"
	Suspended DeploymentStateState = "suspended"
)

// Valid indicates whether the value is a known member of the DeploymentStateState enum.
func (e DeploymentStateState) Valid() bool {
	switch e {
	case Deleting:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Ready:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for ManagedPublicEndpointACLRuleProtocol.
const (
	Tcp ManagedPublicEndpointACLRuleProtocol = "tcp"
	Udp ManagedPublicEndpointACLRuleProtocol = "udp"
)

// Valid indicates whether the value is a known member of the ManagedPublicEndpointACLRuleProtocol enum.
func (e ManagedPublicEndpointACLRuleProtocol) Valid() bool {
	switch e {
	case Tcp:
		return true
	case Udp:
		return true
	default:
		return false
	}
}

// AWSAccountID AWS Account ID.
type AWSAccountID = string

// AWSCloudWatchLogGroup A CloudWatch log group name. Must be 1-512 characters long and consist only of the characters: a-z, A-Z, 0-9, '_', '-', '/', '.', '#'. Must not start with the reserved prefix 'aws/'.
type AWSCloudWatchLogGroup = string

// AWSDeploymentProperties AWS deployment properties.
type AWSDeploymentProperties struct {
	// AccountId AWS Account ID.
	AccountId AWSAccountID `json:"account_id"`

	// Frontend AWS frontend info returned in a deployment response.
	Frontend AWSFrontendInfo `json:"frontend"`

	// Identity Identity info for an AWS-based deployment
	Identity *AWSIdentity `json:"identity,omitempty"`

	// Ipv4CidrBlock IPv4 CIDR block for the deployment VPC. Must be /24 - /18 in size and cannot be within any of these ranges: 0.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4, 172.17.0.0/16
	Ipv4CidrBlock AWSIPv4CIDRBlock `json:"ipv4_cidr_block"`

	// Ipv6CidrBlock IPv6 CIDR block for the deployment VPC.
	Ipv6CidrBlock AWSIPv6CIDRBlock `json:"ipv6_cidr_block"`

	// Monitoring Configuration for exporting deployment logs and metrics.
	Monitoring *AWSMonitoring `json:"monitoring,omitempty"`

	// Region AWS region
	Region AWSRegion `json:"region"`

	// VpcId AWS VPC ID.
	VpcId AWSVpcID `json:"vpc_id"`

	// VpcPeeringConnections List of AWS VPC peering connections between the deployment VPC and upstream network VPCs.
	VpcPeeringConnections AWSVpcPeeringConnections `json:"vpc_peering_connections"`
}

// AWSFrontendInfo AWS frontend info returned in a deployment response.
type AWSFrontendInfo struct {
	// ManagedPublicEndpoint Managed public endpoint info returned in a deployment response.
	ManagedPublicEndpoint *ManagedPublicEndpoint `json:"managed_public_endpoint,omitempty"`

	// PrivateEndpoint AWS private endpoint info returned in a deployment response.
	PrivateEndpoint *AWSPrivateEndpoint `json:"private_endpoint,omitempty"`
}

// AWSIPv4CIDRBlock IPv4 CIDR block for the deployment VPC. Must be /24 - /18 in size and cannot be within any of these ranges: 0.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4, 172.17.0.0/16
type AWSIPv4CIDRBlock = string

// AWSIPv6CIDRBlock IPv6 CIDR block for the deployment VPC.
type AWSIPv6CIDRBlock = string

// AWSIdentity Identity info for an AWS-based deployment
type AWSIdentity struct {
	// CustomerRoleArn The ARN of the IAM role created by the customer for NGINXaaS to assume.
	CustomerRoleArn *AWSRoleARN `json:"customer_role_arn,omitempty"`
}

// AWSMonitoring Configuration for exporting deployment logs and metrics.
type AWSMonitoring struct {
	// Logs Configuration for exporting deployment logs.
	Logs *AWSMonitoringLogs `json:"logs,omitempty"`

	// Metrics Configuration for exporting deployment metrics.
	Metrics *AWSMonitoringMetrics `json:"metrics,omitempty"`
}

// AWSMonitoringLogs Configuration for exporting deployment logs.
type AWSMonitoringLogs struct {
	// CloudwatchGroup A CloudWatch log group name. Must be 1-512 characters long and consist only of the characters: a-z, A-Z, 0-9, '_', '-', '/', '.', '#'. Must not start with the reserved prefix 'aws/'.
	CloudwatchGroup *AWSCloudWatchLogGroup `json:"cloudwatch_group,omitempty"`

	// Enabled Whether exporting deployment logs is enabled.
	Enabled *bool `json:"enabled,omitempty"`
}

// AWSMonitoringMetrics Configuration for exporting deployment metrics.
type AWSMonitoringMetrics struct {
	// CloudwatchGroup A CloudWatch log group name. Must be 1-512 characters long and consist only of the characters: a-z, A-Z, 0-9, '_', '-', '/', '.', '#'. Must not start with the reserved prefix 'aws/'.
	CloudwatchGroup *AWSCloudWatchLogGroup `json:"cloudwatch_group,omitempty"`

	// Enabled Whether exporting deployment metrics is enabled.
	Enabled *bool `json:"enabled,omitempty"`
}

// AWSPrivateEndpoint AWS private endpoint info returned in a deployment response.
type AWSPrivateEndpoint struct {
	// PrivateLinkConnectionAllowList List of AWS Account IDs or VPC Endpoint IDs that are allowed to connect. The list must contain either all account IDs or all VPC endpoint IDs (cannot mix). An empty list indicates no connections should be allowed.
	PrivateLinkConnectionAllowList *AWSPrivateLinkConnectionAllowList `json:"private_link_connection_allow_list,omitempty"`

	// PrivateLinkServiceEndpointName The name of the AWS PrivateLink service endpoint for the deployment.
	PrivateLinkServiceEndpointName *AWSPrivateLinkServiceEndpointName `json:"private_link_service_endpoint_name,omitempty"`
}

// AWSPrivateLinkConnectionAllowList List of AWS Account IDs or VPC Endpoint IDs that are allowed to connect. The list must contain either all account IDs or all VPC endpoint IDs (cannot mix). An empty list indicates no connections should be allowed.
type AWSPrivateLinkConnectionAllowList = []AWSPrivateLinkConnectionAllowListItem

// AWSPrivateLinkConnectionAllowListItem An item in the allow list for AWS PrivateLink connections.
type AWSPrivateLinkConnectionAllowListItem = string

// AWSPrivateLinkServiceEndpointName The name of the AWS PrivateLink service endpoint for the deployment.
type AWSPrivateLinkServiceEndpointName = string

// AWSRegion AWS region
type AWSRegion = string

// AWSRoleARN Amazon Resource Name (ARN) for an IAM role
type AWSRoleARN = string

// AWSVpcEndpointID AWS VPC Endpoint ID.
type AWSVpcEndpointID = string

// AWSVpcID AWS VPC ID.
type AWSVpcID = string

// AWSVpcPeeringConnectionID AWS VPC peering connection ID.
type AWSVpcPeeringConnectionID = string

// AWSVpcPeeringConnections List of AWS VPC peering connections between the deployment VPC and upstream network VPCs.
type AWSVpcPeeringConnections = []AWSVpcPeeringConnectionID

// AzureDeploymentProperties Azure deployment properties.
type AzureDeploymentProperties struct {
	// Ipv4CidrBlock IPv4 CIDR block for the azure deployment VNet, e.g. "172.25.0.0/25". Must be /8 - /25 in size and cannot be within any of these ranges: 255.255.255.255/32, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4, 168.63.129.16/32
	Ipv4CidrBlock AzureIPv4CIDRBlock `json:"ipv4_cidr_block"`

	// Ipv6CidrBlock IPv6 CIDR block for the azure deployment VNet, e.g. "fd54:60a3:e830::/48". Either provided by the consumer or, if omitted, the deployment-svc generates a random ULA /48. Must be between /7 and /63 in prefix length.
	Ipv6CidrBlock AzureIPv6CIDRBlock `json:"ipv6_cidr_block"`

	// Region Azure region. Must match the programmatic name from https://learn.microsoft.com/en-us/azure/reliability/regions-list.
	Region AzureRegion `json:"region"`
}

// AzureIPv4CIDRBlock IPv4 CIDR block for the azure deployment VNet, e.g. "172.25.0.0/25". Must be /8 - /25 in size and cannot be within any of these ranges: 255.255.255.255/32, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4, 168.63.129.16/32
type AzureIPv4CIDRBlock = string

// AzureIPv6CIDRBlock IPv6 CIDR block for the azure deployment VNet, e.g. "fd54:60a3:e830::/48". Either provided by the consumer or, if omitted, the deployment-svc generates a random ULA /48. Must be between /7 and /63 in prefix length.
type AzureIPv6CIDRBlock = string

// AzureRegion Azure region. Must match the programmatic name from https://learn.microsoft.com/en-us/azure/reliability/regions-list.
type AzureRegion = string

// CreateAWSDeploymentProperties AWS deployment properties used in a create request.
type CreateAWSDeploymentProperties struct {
	// Frontend AWS frontend info used in a create request.
	Frontend CreateAWSFrontendInfo `json:"frontend"`
	Identity *CreateAWSIdentity    `json:"identity,omitempty"`

	// Ipv4CidrBlock IPv4 CIDR block for the deployment VPC. Must be /24 - /18 in size and cannot be within any of these ranges: 0.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4, 172.17.0.0/16
	Ipv4CidrBlock AWSIPv4CIDRBlock `json:"ipv4_cidr_block"`

	// Monitoring Configuration for exporting deployment logs and metrics.
	Monitoring *AWSMonitoring `json:"monitoring,omitempty"`

	// Region AWS region
	Region AWSRegion `json:"region"`
}

// CreateAWSFrontendInfo AWS frontend info used in a create request.
type CreateAWSFrontendInfo struct {
	// ManagedPublicEndpoint Managed public endpoint info used in a create request.
	ManagedPublicEndpoint *CreateManagedPublicEndpoint `json:"managed_public_endpoint,omitempty"`

	// PrivateEndpoint AWS private endpoint info returned in a deployment response.
	PrivateEndpoint *AWSPrivateEndpoint `json:"private_endpoint,omitempty"`
}

// CreateAWSIdentity defines model for CreateAWSIdentity.
type CreateAWSIdentity struct {
	// CustomerRoleArn The ARN of the IAM role created by the customer for NGINXaaS to assume.
	CustomerRoleArn AWSRoleARN `json:"customer_role_arn"`
}

// CreateAzureDeploymentProperties Azure deployment properties used in a create request.
type CreateAzureDeploymentProperties struct {
	// Ipv4CidrBlock IPv4 CIDR block for the azure deployment VNet, e.g. "172.25.0.0/25". Must be /8 - /25 in size and cannot be within any of these ranges: 255.255.255.255/32, 127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4, 168.63.129.16/32
	Ipv4CidrBlock AzureIPv4CIDRBlock `json:"ipv4_cidr_block"`

	// Ipv6CidrBlock IPv6 CIDR block for the azure deployment VNet, e.g. "fd54:60a3:e830::/48". Either provided by the consumer or, if omitted, the deployment-svc generates a random ULA /48. Must be between /7 and /63 in prefix length.
	Ipv6CidrBlock *AzureIPv6CIDRBlock `json:"ipv6_cidr_block,omitempty"`

	// Region Azure region. Must match the programmatic name from https://learn.microsoft.com/en-us/azure/reliability/regions-list.
	Region AzureRegion `json:"region"`
}

// CreateDeploymentCloudProperties Cloud-specific create properties.
type CreateDeploymentCloudProperties struct {
	// Aws AWS deployment properties used in a create request.
	Aws *CreateAWSDeploymentProperties `json:"aws,omitempty"`

	// Azure Azure deployment properties used in a create request.
	Azure *CreateAzureDeploymentProperties `json:"azure,omitempty"`

	// Google Google deployment properties used in a create request.
	Google *CreateGoogleDeploymentProperties `json:"google,omitempty"`
}

// CreateGoogleDeploymentProperties Google deployment properties used in a create request.
type CreateGoogleDeploymentProperties struct {
	// Frontend Google frontend info used in a create request.
	Frontend CreateGoogleFrontendInfo `json:"frontend"`

	// Identity Identity info for a Google-based deployment used in a create or update request
	Identity *CreateGoogleIdentity `json:"identity,omitempty"`

	// LogProjectId The Google Cloud project ID where NGINX logs will be exported. Omit the field to disable log exporting.
	LogProjectId *GoogleProjectID `json:"log_project_id,omitempty"`

	// MetricProjectId The Google Cloud project ID where NGINXaaS metrics will be exported. Omit the field to disable metric exporting.
	MetricProjectId *GoogleProjectID `json:"metric_project_id,omitempty"`

	// NetworkAttachment Google network attachment.
	NetworkAttachment GoogleNetworkAttachment `json:"network_attachment"`
	Region            GoogleRegion            `json:"region"`
}

// CreateGoogleFrontendInfo Google frontend info used in a create request.
type CreateGoogleFrontendInfo struct {
	// ManagedPublicEndpoint Managed public endpoint info used in a create request.
	ManagedPublicEndpoint *CreateManagedPublicEndpoint `json:"managed_public_endpoint,omitempty"`

	// PrivateEndpoint Google private endpoint info used in a create or update request.
	PrivateEndpoint *UpdateGooglePrivateEndpoint `json:"private_endpoint,omitempty"`
}

// CreateGoogleIdentity Identity info for a Google-based deployment used in a create or update request
type CreateGoogleIdentity struct {
	// WorkloadIdentityPoolProviderName The resource name of the Google workload identity pool provider
	WorkloadIdentityPoolProviderName *GoogleWorkloadIdentityPoolProviderName `json:"workload_identity_pool_provider_name,omitempty"`
}

// CreateManagedPublicEndpoint Managed public endpoint info used in a create request.
type CreateManagedPublicEndpoint struct {
	// Acl Access control list for the managed public endpoint. Maximum of 40 rules.
	Acl ManagedPublicEndpointACL `json:"acl"`
}

// Deployment Deployment specification.
type Deployment struct {
	// Cloud Name of the cloud where deployment resources are provisioned.
	Cloud DeploymentCloudName `json:"cloud"`

	// CloudProperties Cloud-specific deployment properties.
	CloudProperties DeploymentCloudProperties `json:"cloud_properties"`

	// CreatedAt Datetime when request to create deployment was received.
	CreatedAt time.Time `json:"created_at"`

	// DeletedAt Datetime when request to delete deployment was received.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// Description Description of a resource.
	Description externalRef0.NginxaasDescription `json:"description"`

	// Id A globally unique identifier for the deployment.
	Id externalRef0.DeploymentObjectID `json:"id"`

	// ModifiedAt Datetime when deployment was last modified.
	ModifiedAt time.Time `json:"modified_at"`

	// Name Name of an NGINXaaS resource.
	Name DeploymentName `json:"name"`

	// NginxConfigId A globally unique identifier for the NGINX config.
	NginxConfigId externalRef0.NginxaasNginxConfigObjectID `json:"nginx_config_id"`

	// NginxConfigVersionId NGINX config version object id
	NginxConfigVersionId externalRef0.NginxaasNginxConfigVersionObjectID `json:"nginx_config_version_id"`

	// OrganizationId NGINXaaS organization id
	OrganizationId externalRef0.NginxaasOrganizationID `json:"organization_id"`

	// Scale NaaS deployment scale info.
	Scale DeploymentScale `json:"scale"`

	// Status Deployment status info.
	Status DeploymentStatus `json:"status"`

	// WafEnabled Whether WAF is enabled for the deployment.
	WafEnabled *WafEnabled `json:"waf_enabled,omitempty"`
}

// DeploymentCloudName Name of the cloud where deployment resources are provisioned.
type DeploymentCloudName string

// DeploymentCloudProperties Cloud-specific deployment properties.
type DeploymentCloudProperties struct {
	// Aws AWS deployment properties.
	Aws *AWSDeploymentProperties `json:"aws,omitempty"`

	// Azure Azure deployment properties.
	Azure *AzureDeploymentProperties `json:"azure,omitempty"`

	// Google Google deployment properties.
	Google *GoogleDeploymentProperties `json:"google,omitempty"`
}

// DeploymentConfigState Deployment state info
type DeploymentConfigState = DeploymentState

// DeploymentCreateRequest Request spec for creating a deployment.
type DeploymentCreateRequest struct {
	// CloudProperties Cloud-specific create properties.
	CloudProperties CreateDeploymentCloudProperties `json:"cloud_properties"`

	// Description Description of a resource.
	Description *externalRef0.NginxaasDescription `json:"description,omitempty"`

	// Name Name of an NGINXaaS resource.
	Name DeploymentName `json:"name"`

	// NginxConfigId A globally unique identifier for the NGINX config.
	NginxConfigId externalRef0.NginxaasNginxConfigObjectID `json:"nginx_config_id"`

	// NginxConfigVersionId NGINX config version object id
	NginxConfigVersionId externalRef0.NginxaasNginxConfigVersionObjectID `json:"nginx_config_version_id"`

	// Scale NaaS deployment scale info.
	Scale DeploymentScale `json:"scale"`

	// WafEnabled Whether WAF is enabled for the deployment.
	WafEnabled *WafEnabled `json:"waf_enabled,omitempty"`
}

// DeploymentListResponse List of deployments.
type DeploymentListResponse struct {
	// Count The total number of deployments returned.
	Count int          `json:"count"`
	Items []Deployment `json:"items"`
}

// DeploymentName Name of an NGINXaaS resource.
type DeploymentName = string

// DeploymentProvisioningState Deployment state info
type DeploymentProvisioningState = DeploymentState

// DeploymentScale NaaS deployment scale info.
type DeploymentScale struct {
	// Capacity The number of desired NCUs for a NaaS deployment. Must be >= 10, <= 500.
	Capacity int `json:"capacity"`
}

// DeploymentState Deployment state info
type DeploymentState struct {
	// Details State details.
	Details *string `json:"details,omitempty"`

	// ModifiedAt Datetime of last state change.
	ModifiedAt time.Time `json:"modified_at"`

	// State State name/value.
	State DeploymentStateState `json:"state"`
}

// DeploymentStateState State name/value.
type DeploymentStateState string

// DeploymentStatus Deployment status info.
type DeploymentStatus struct {
	// ConfigState Deployment state info
	ConfigState DeploymentConfigState `json:"config_state"`

	// NginxTargetVersion Target nginx version in deployment
	NginxTargetVersion string `json:"nginx_target_version"`

	// ProvisioningState Deployment state info
	ProvisioningState DeploymentProvisioningState `json:"provisioning_state"`

	// WafVersion The WAF version currently active on the deployment. Only populated if WAF is enabled
	WafVersion *string `json:"waf_version,omitempty"`
}

// DeploymentUpdateRequest Request spec for updating a deployment.
type DeploymentUpdateRequest struct {
	// CloudProperties Cloud-specific update properties.
	CloudProperties *UpdateDeploymentCloudProperties `json:"cloud_properties,omitempty"`

	// Description Description of a resource.
	Description *externalRef0.NginxaasDescription `json:"description,omitempty"`

	// NginxConfigId A globally unique identifier for the NGINX config.
	NginxConfigId *externalRef0.NginxaasNginxConfigObjectID `json:"nginx_config_id,omitempty"`

	// NginxConfigVersionId NGINX config version object id
	NginxConfigVersionId *externalRef0.NginxaasNginxConfigVersionObjectID `json:"nginx_config_version_id,omitempty"`

	// Scale NaaS deployment scale info.
	Scale *DeploymentScale `json:"scale,omitempty"`

	// WafEnabled Whether WAF is enabled for the deployment.
	WafEnabled *WafEnabled `json:"waf_enabled,omitempty"`
}

// EmptyStringOrAWSRoleARN Amazon Resource Name (ARN) for an IAM role, allowing empty strings
type EmptyStringOrAWSRoleARN = string

// EmptyStringOrGoogleProjectID defines model for EmptyStringOrGoogleProjectID.
type EmptyStringOrGoogleProjectID = string

// EmptyStringOrGoogleWorkloadIdentityPoolProviderName The resource name of the Google workload identity pool provider
type EmptyStringOrGoogleWorkloadIdentityPoolProviderName = string

// GoogleDeploymentProperties Google deployment properties.
type GoogleDeploymentProperties struct {
	// Frontend Google frontend info returned in a deployment response.
	Frontend GoogleFrontendInfo `json:"frontend"`

	// Identity Identity info for a Google-based deployment
	Identity *GoogleIdentity `json:"identity,omitempty"`

	// LogProjectId The Google Cloud project ID where NGINX logs will be exported.
	LogProjectId *GoogleProjectID `json:"log_project_id,omitempty"`

	// MetricProjectId The Google Cloud project ID where NGINXaaS metrics will be exported.
	MetricProjectId *GoogleProjectID `json:"metric_project_id,omitempty"`

	// NetworkAttachment Google network attachment.
	NetworkAttachment GoogleNetworkAttachment `json:"network_attachment"`

	// ProjectId The Google Cloud project ID where this deployment resides. This project_id can be used for the network attachment allowlist.
	ProjectId GoogleProjectID `json:"project_id"`
	Region    GoogleRegion    `json:"region"`
}

// GoogleFrontendInfo Google frontend info returned in a deployment response.
type GoogleFrontendInfo struct {
	// ManagedPublicEndpoint Managed public endpoint info returned in a deployment response.
	ManagedPublicEndpoint *ManagedPublicEndpoint `json:"managed_public_endpoint,omitempty"`

	// PrivateEndpoint Google private endpoint info returned in a deployment response.
	PrivateEndpoint *GooglePrivateEndpoint `json:"private_endpoint,omitempty"`
}

// GoogleIdentity Identity info for a Google-based deployment
type GoogleIdentity struct {
	// NginxaasServiceAccountUniqueId The unique numeric ID of the Google service account created by NGINXaaS
	NginxaasServiceAccountUniqueId *GoogleServiceAccountUniqueID `json:"nginxaas_service_account_unique_id,omitempty"`

	// WorkloadIdentityPoolProviderName The resource name of the Google workload identity pool provider
	WorkloadIdentityPoolProviderName *GoogleWorkloadIdentityPoolProviderName `json:"workload_identity_pool_provider_name,omitempty"`
}

// GoogleNetworkAttachment Google network attachment.
type GoogleNetworkAttachment = string

// GooglePrivateEndpoint Google private endpoint info returned in a deployment response.
type GooglePrivateEndpoint struct {
	// ServiceAttachment Google service attachment.
	ServiceAttachment *GoogleServiceAttachment `json:"service_attachment,omitempty"`

	// ServiceAttachmentAcceptList List of google networkURls or project ids that should connect to the service attachment. The list must contain either all network urls or all project ids but not both simultaneously. An empty list indicates all connections to the service attachment should be accepted.
	ServiceAttachmentAcceptList *GoogleServiceAttachmentAcceptList `json:"service_attachment_accept_list,omitempty"`
}

// GoogleProjectID defines model for GoogleProjectID.
type GoogleProjectID = string

// GoogleRegion defines model for GoogleRegion.
type GoogleRegion = GoogleResourceName

// GoogleResourceName defines model for GoogleResourceName.
type GoogleResourceName = string

// GoogleServiceAccountUniqueID The unique numeric ID of the Google service account
type GoogleServiceAccountUniqueID = string

// GoogleServiceAttachment Google service attachment.
type GoogleServiceAttachment = string

// GoogleServiceAttachmentAcceptList List of google networkURls or project ids that should connect to the service attachment. The list must contain either all network urls or all project ids but not both simultaneously. An empty list indicates all connections to the service attachment should be accepted.
type GoogleServiceAttachmentAcceptList = []GoogleServiceAttachmentAcceptListItem

// GoogleServiceAttachmentAcceptListItem defines model for GoogleServiceAttachmentAcceptListItem.
type GoogleServiceAttachmentAcceptListItem = string

// GoogleServiceAttachmentAcceptNetworkItem defines model for GoogleServiceAttachmentAcceptNetworkItem.
type GoogleServiceAttachmentAcceptNetworkItem = string

// GoogleWorkloadIdentityPoolProviderName The resource name of the Google workload identity pool provider
type GoogleWorkloadIdentityPoolProviderName = string

// ManagedPublicEndpoint Managed public endpoint info returned in a deployment response.
type ManagedPublicEndpoint struct {
	// Acl Access control list for the managed public endpoint. Maximum of 40 rules.
	Acl ManagedPublicEndpointACL `json:"acl"`

	// ServiceEndpoint The public DNS name for the managed public endpoint.
	ServiceEndpoint *string `json:"service_endpoint,omitempty"`
}

// ManagedPublicEndpointACL Access control list for the managed public endpoint. Maximum of 40 rules.
type ManagedPublicEndpointACL = []ManagedPublicEndpointACLRule

// ManagedPublicEndpointACLRule A single ACL rule for the managed public endpoint.
type ManagedPublicEndpointACLRule struct {
	// Description Optional description for the ACL rule.
	Description *string `json:"description,omitempty"`

	// PortRange Port range as either a single integer or a range separated by dash, inclusive. Must be specified if protocol is specified.
	PortRange *string `json:"port_range,omitempty"`

	// Protocol Network protocol for the rule. Must be specified if port_range is specified.
	Protocol *ManagedPublicEndpointACLRuleProtocol `json:"protocol,omitempty"`

	// SourcePrefixes List of CIDR blocks.
	SourcePrefixes []string `json:"source_prefixes"`
	union          json.RawMessage
}

// ManagedPublicEndpointACLRuleProtocol Network protocol for the rule. Must be specified if port_range is specified.
type ManagedPublicEndpointACLRuleProtocol string

// ManagedPublicEndpointACLRule0 defines model for .
type ManagedPublicEndpointACLRule0 = interface{}

// ManagedPublicEndpointACLRule1 defines model for .
type ManagedPublicEndpointACLRule1 = interface{}

// UpdateAWSDeploymentProperties AWS deployment properties used in an update request.
type UpdateAWSDeploymentProperties struct {
	// Frontend AWS frontend info used in an update request.
	Frontend *UpdateAWSFrontendInfo `json:"frontend,omitempty"`

	// Identity Identity info for an AWS-based deployment
	Identity *UpdateAWSIdentity `json:"identity,omitempty"`

	// Monitoring Configuration for exporting deployment logs and metrics.
	Monitoring *AWSMonitoring `json:"monitoring,omitempty"`

	// VpcPeeringConnections List of AWS VPC peering connections between the deployment VPC and upstream network VPCs.
	VpcPeeringConnections *AWSVpcPeeringConnections `json:"vpc_peering_connections,omitempty"`
}

// UpdateAWSFrontendInfo AWS frontend info used in an update request.
type UpdateAWSFrontendInfo struct {
	// ManagedPublicEndpoint Managed public endpoint info used in an update request.
	ManagedPublicEndpoint *UpdateManagedPublicEndpoint `json:"managed_public_endpoint,omitempty"`

	// PrivateEndpoint AWS private endpoint info returned in a deployment response.
	PrivateEndpoint *AWSPrivateEndpoint `json:"private_endpoint,omitempty"`
}

// UpdateAWSIdentity Identity info for an AWS-based deployment
type UpdateAWSIdentity struct {
	// CustomerRoleArn The ARN of the IAM role created by the customer for NGINXaaS to assume, or empty string to remove an existing role.
	CustomerRoleArn *EmptyStringOrAWSRoleARN `json:"customer_role_arn,omitempty"`
}

// UpdateAzureDeploymentProperties Azure deployment properties used in an update request.
type UpdateAzureDeploymentProperties = map[string]interface{}

// UpdateDeploymentCloudProperties Cloud-specific update properties.
type UpdateDeploymentCloudProperties struct {
	// Aws AWS deployment properties used in an update request.
	Aws *UpdateAWSDeploymentProperties `json:"aws,omitempty"`

	// Azure Azure deployment properties used in an update request.
	Azure *UpdateAzureDeploymentProperties `json:"azure,omitempty"`

	// Google Google deployment properties used in an update request.
	Google *UpdateGoogleDeploymentProperties `json:"google,omitempty"`
}

// UpdateGoogleDeploymentProperties Google deployment properties used in an update request.
type UpdateGoogleDeploymentProperties struct {
	// Frontend Google frontend info used in an update request.
	Frontend *UpdateGoogleFrontendInfo `json:"frontend,omitempty"`

	// Identity Identity info for a Google-based deployment used in a create or update request
	Identity *UpdateGoogleIdentity `json:"identity,omitempty"`

	// LogProjectId The Google Cloud project ID where NGINX logs will be exported. Set to an empty string to disable log exporting.
	LogProjectId *EmptyStringOrGoogleProjectID `json:"log_project_id,omitempty"`

	// MetricProjectId The Google Cloud project ID where NGINXaaS metrics will be exported. Set to an empty string to disable metric exporting.
	MetricProjectId *EmptyStringOrGoogleProjectID `json:"metric_project_id,omitempty"`
}

// UpdateGoogleFrontendInfo Google frontend info used in an update request.
type UpdateGoogleFrontendInfo struct {
	// ManagedPublicEndpoint Managed public endpoint info used in an update request.
	ManagedPublicEndpoint *UpdateManagedPublicEndpoint `json:"managed_public_endpoint,omitempty"`

	// PrivateEndpoint Google private endpoint info used in a create or update request.
	PrivateEndpoint *UpdateGooglePrivateEndpoint `json:"private_endpoint,omitempty"`
}

// UpdateGoogleIdentity Identity info for a Google-based deployment used in a create or update request
type UpdateGoogleIdentity struct {
	// WorkloadIdentityPoolProviderName The resource name of the Google workload identity pool provider
	WorkloadIdentityPoolProviderName *EmptyStringOrGoogleWorkloadIdentityPoolProviderName `json:"workload_identity_pool_provider_name,omitempty"`
}

// UpdateGooglePrivateEndpoint Google private endpoint info used in a create or update request.
type UpdateGooglePrivateEndpoint struct {
	// ServiceAttachmentAcceptList List of google networkURls or project ids that should connect to the service attachment. The list must contain either all network urls or all project ids but not both simultaneously. An empty list indicates all connections to the service attachment should be accepted.
	ServiceAttachmentAcceptList *GoogleServiceAttachmentAcceptList `json:"service_attachment_accept_list,omitempty"`
}

// UpdateManagedPublicEndpoint Managed public endpoint info used in an update request.
type UpdateManagedPublicEndpoint struct {
	// Acl Access control list for the managed public endpoint. Maximum of 40 rules.
	Acl *ManagedPublicEndpointACL `json:"acl,omitempty"`
}

// WafEnabled Whether WAF is enabled for the deployment.
type WafEnabled = bool

// DeploymentObjectID A globally unique identifier for the deployment.
type DeploymentObjectID = externalRef0.DeploymentObjectID

// CreateDeploymentJSONRequestBody defines body for CreateDeployment for application/json ContentType.
type CreateDeploymentJSONRequestBody = DeploymentCreateRequest

// UpdateDeploymentJSONRequestBody defines body for UpdateDeployment for application/json ContentType.
type UpdateDeploymentJSONRequestBody = DeploymentUpdateRequest

// AsManagedPublicEndpointACLRule0 returns the union data inside the ManagedPublicEndpointACLRule as a ManagedPublicEndpointACLRule0
func (t ManagedPublicEndpointACLRule) AsManagedPublicEndpointACLRule0() (ManagedPublicEndpointACLRule0, error) {
	var body ManagedPublicEndpointACLRule0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromManagedPublicEndpointACLRule0 overwrites any union data inside the ManagedPublicEndpointACLRule as the provided ManagedPublicEndpointACLRule0
func (t *ManagedPublicEndpointACLRule) FromManagedPublicEndpointACLRule0(v ManagedPublicEndpointACLRule0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeManagedPublicEndpointACLRule0 performs a merge with any union data inside the ManagedPublicEndpointACLRule, using the provided ManagedPublicEndpointACLRule0
func (t *ManagedPublicEndpointACLRule) MergeManagedPublicEndpointACLRule0(v ManagedPublicEndpointACLRule0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsManagedPublicEndpointACLRule1 returns the union data inside the ManagedPublicEndpointACLRule as a ManagedPublicEndpointACLRule1
func (t ManagedPublicEndpointACLRule) AsManagedPublicEndpointACLRule1() (ManagedPublicEndpointACLRule1, error) {
	var body ManagedPublicEndpointACLRule1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromManagedPublicEndpointACLRule1 overwrites any union data inside the ManagedPublicEndpointACLRule as the provided ManagedPublicEndpointACLRule1
func (t *ManagedPublicEndpointACLRule) FromManagedPublicEndpointACLRule1(v ManagedPublicEndpointACLRule1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeManagedPublicEndpointACLRule1 performs a merge with any union data inside the ManagedPublicEndpointACLRule, using the provided ManagedPublicEndpointACLRule1
func (t *ManagedPublicEndpointACLRule) MergeManagedPublicEndpointACLRule1(v ManagedPublicEndpointACLRule1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ManagedPublicEndpointACLRule) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Description != nil {
		object["description"], err = json.Marshal(t.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	if t.PortRange != nil {
		object["port_range"], err = json.Marshal(t.PortRange)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'port_range': %w", err)
		}
	}

	if t.Protocol != nil {
		object["protocol"], err = json.Marshal(t.Protocol)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'protocol': %w", err)
		}
	}

	if t.SourcePrefixes != nil {
		object["source_prefixes"], err = json.Marshal(t.SourcePrefixes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'source_prefixes': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *ManagedPublicEndpointACLRule) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["port_range"]; found {
		err = json.Unmarshal(raw, &t.PortRange)
		if err != nil {
			return fmt.Errorf("error reading 'port_range': %w", err)
		}
	}

	if raw, found := object["protocol"]; found {
		err = json.Unmarshal(raw, &t.Protocol)
		if err != nil {
			return fmt.Errorf("error reading 'protocol': %w", err)
		}
	}

	if raw, found := object["source_prefixes"]; found {
		err = json.Unmarshal(raw, &t.SourcePrefixes)
		if err != nil {
			return fmt.Errorf("error reading 'source_prefixes': %w", err)
		}
	}

	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListDeployments request
	ListDeployments(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDeploymentWithBody request with any body
	CreateDeploymentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDeployment(ctx context.Context, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDeployment request
	DeleteDeployment(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeployment request
	GetDeployment(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDeploymentWithBody request with any body
	UpdateDeploymentWithBody(ctx context.Context, deploymentId DeploymentObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateDeployment(ctx context.Context, deploymentId DeploymentObjectID, body UpdateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListDeployments(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDeploymentsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeploymentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeploymentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeployment(ctx context.Context, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeploymentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDeployment(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDeploymentRequest(c.Server, deploymentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeployment(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeploymentRequest(c.Server, deploymentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDeploymentWithBody(ctx context.Context, deploymentId DeploymentObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDeploymentRequestWithBody(c.Server, deploymentId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDeployment(ctx context.Context, deploymentId DeploymentObjectID, body UpdateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDeploymentRequest(c.Server, deploymentId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDeploymentsRequest generates requests for ListDeployments
func NewListDeploymentsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/deployments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDeploymentRequest calls the generic CreateDeployment builder with application/json body
func NewCreateDeploymentRequest(server string, body CreateDeploymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDeploymentRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDeploymentRequestWithBody generates requests for CreateDeployment with any type of body
func NewCreateDeploymentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/deployments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDeploymentRequest generates requests for DeleteDeployment
func NewDeleteDeploymentRequest(server string, deploymentId DeploymentObjectID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment_id", deploymentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/deployments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeploymentRequest generates requests for GetDeployment
func NewGetDeploymentRequest(server string, deploymentId DeploymentObjectID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment_id", deploymentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/deployments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateDeploymentRequest calls the generic UpdateDeployment builder with application/json body
func NewUpdateDeploymentRequest(server string, deploymentId DeploymentObjectID, body UpdateDeploymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDeploymentRequestWithBody(server, deploymentId, "application/json", bodyReader)
}

// NewUpdateDeploymentRequestWithBody generates requests for UpdateDeployment with any type of body
func NewUpdateDeploymentRequestWithBody(server string, deploymentId DeploymentObjectID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment_id", deploymentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "object_id"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/deployments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListDeploymentsWithResponse request
	ListDeploymentsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDeploymentsResponse, error)

	// CreateDeploymentWithBodyWithResponse request with any body
	CreateDeploymentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error)

	CreateDeploymentWithResponse(ctx context.Context, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error)

	// DeleteDeploymentWithResponse request
	DeleteDeploymentWithResponse(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*DeleteDeploymentResponse, error)

	// GetDeploymentWithResponse request
	GetDeploymentWithResponse(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*GetDeploymentResponse, error)

	// UpdateDeploymentWithBodyWithResponse request with any body
	UpdateDeploymentWithBodyWithResponse(ctx context.Context, deploymentId DeploymentObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDeploymentResponse, error)

	UpdateDeploymentWithResponse(ctx context.Context, deploymentId DeploymentObjectID, body UpdateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDeploymentResponse, error)
}

type ListDeploymentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeploymentListResponse
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r ListDeploymentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDeploymentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDeploymentsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Deployment
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON403      *externalRef0.Forbidden
	JSON409      *externalRef0.Conflict
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r CreateDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateDeploymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Deployment
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r DeleteDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteDeploymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Deployment
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON404      *externalRef0.NotFound
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r GetDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDeploymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Deployment
	JSON400      *externalRef0.InvalidRequest
	JSON401      *externalRef0.Unauthorized
	JSON403      *externalRef0.Forbidden
	JSON404      *externalRef0.NotFound
	JSON409      *externalRef0.Conflict
	JSON500      *externalRef0.InternalServerErr
}

// Status returns HTTPResponse.Status
func (r UpdateDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateDeploymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListDeploymentsWithResponse request returning *ListDeploymentsResponse
func (c *ClientWithResponses) ListDeploymentsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDeploymentsResponse, error) {
	rsp, err := c.ListDeployments(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDeploymentsResponse(rsp)
}

// CreateDeploymentWithBodyWithResponse request with arbitrary body returning *CreateDeploymentResponse
func (c *ClientWithResponses) CreateDeploymentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error) {
	rsp, err := c.CreateDeploymentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeploymentResponse(rsp)
}

func (c *ClientWithResponses) CreateDeploymentWithResponse(ctx context.Context, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error) {
	rsp, err := c.CreateDeployment(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeploymentResponse(rsp)
}

// DeleteDeploymentWithResponse request returning *DeleteDeploymentResponse
func (c *ClientWithResponses) DeleteDeploymentWithResponse(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*DeleteDeploymentResponse, error) {
	rsp, err := c.DeleteDeployment(ctx, deploymentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDeploymentResponse(rsp)
}

// GetDeploymentWithResponse request returning *GetDeploymentResponse
func (c *ClientWithResponses) GetDeploymentWithResponse(ctx context.Context, deploymentId DeploymentObjectID, reqEditors ...RequestEditorFn) (*GetDeploymentResponse, error) {
	rsp, err := c.GetDeployment(ctx, deploymentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeploymentResponse(rsp)
}

// UpdateDeploymentWithBodyWithResponse request with arbitrary body returning *UpdateDeploymentResponse
func (c *ClientWithResponses) UpdateDeploymentWithBodyWithResponse(ctx context.Context, deploymentId DeploymentObjectID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDeploymentResponse, error) {
	rsp, err := c.UpdateDeploymentWithBody(ctx, deploymentId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDeploymentResponse(rsp)
}

func (c *ClientWithResponses) UpdateDeploymentWithResponse(ctx context.Context, deploymentId DeploymentObjectID, body UpdateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDeploymentResponse, error) {
	rsp, err := c.UpdateDeployment(ctx, deploymentId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDeploymentResponse(rsp)
}

// ParseListDeploymentsResponse parses an HTTP response from a ListDeploymentsWithResponse call
func ParseListDeploymentsResponse(rsp *http.Response) (*ListDeploymentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDeploymentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeploymentListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateDeploymentResponse parses an HTTP response from a CreateDeploymentWithResponse call
func ParseCreateDeploymentResponse(rsp *http.Response) (*CreateDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteDeploymentResponse parses an HTTP response from a DeleteDeploymentWithResponse call
func ParseDeleteDeploymentResponse(rsp *http.Response) (*DeleteDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetDeploymentResponse parses an HTTP response from a GetDeploymentWithResponse call
func ParseGetDeploymentResponse(rsp *http.Response) (*GetDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateDeploymentResponse parses an HTTP response from a UpdateDeploymentWithResponse call
func ParseUpdateDeploymentResponse(rsp *http.Response) (*UpdateDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErr
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
