user nginx;
worker_processes auto;
pid /run/nginx/nginx.pid;

events {
    worker_connections 768;
}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 "Hello from F5 ADS NGINX\n";
        }
    }
}
