// Package naas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package naas

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"

	objects "github.com/F5Networks/terraform-provider-f5ads/internal/provider/objects"
	xp "github.com/nginxinc/nginx-go-crossplane"
)

// Defines values for CertificateStatus.
const (
	CertificateStatusExpired  CertificateStatus = "expired"
	CertificateStatusExpiring CertificateStatus = "expiring"
	CertificateStatusNotReady CertificateStatus = "not_ready"
	CertificateStatusValid    CertificateStatus = "valid"
)

// Valid indicates whether the value is a known member of the CertificateStatus enum.
func (e CertificateStatus) Valid() bool {
	switch e {
	case CertificateStatusExpired:
		return true
	case CertificateStatusExpiring:
		return true
	case CertificateStatusNotReady:
		return true
	case CertificateStatusValid:
		return true
	default:
		return false
	}
}

// Defines values for EventType.
const (
	EventTypeCertificates       EventType = "certificates"
	EventTypeInstanceCleanup    EventType = "instance_cleanup"
	EventTypeNapCompilationJobs EventType = "nap_compilation_jobs"
	EventTypePublications       EventType = "publications"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case EventTypeCertificates:
		return true
	case EventTypeInstanceCleanup:
		return true
	case EventTypeNapCompilationJobs:
		return true
	case EventTypePublications:
		return true
	default:
		return false
	}
}

// Defines values for FilterNameCertificateDeployments.
const (
	FilterNameCertificateDeploymentsAssociationType  FilterNameCertificateDeployments = "association_type"
	FilterNameCertificateDeploymentsDeploymentStatus FilterNameCertificateDeployments = "deployment_status"
	FilterNameCertificateDeploymentsName             FilterNameCertificateDeployments = "name"
)

// Valid indicates whether the value is a known member of the FilterNameCertificateDeployments enum.
func (e FilterNameCertificateDeployments) Valid() bool {
	switch e {
	case FilterNameCertificateDeploymentsAssociationType:
		return true
	case FilterNameCertificateDeploymentsDeploymentStatus:
		return true
	case FilterNameCertificateDeploymentsName:
		return true
	default:
		return false
	}
}

// Defines values for FilterNameEvents.
const (
	FilterNameEventsObjectId FilterNameEvents = "object_id"
)

// Valid indicates whether the value is a known member of the FilterNameEvents enum.
func (e FilterNameEvents) Valid() bool {
	switch e {
	case FilterNameEventsObjectId:
		return true
	default:
		return false
	}
}

// Defines values for FilterOperand.
const (
	FilterOperandsIn FilterOperand = "IN"
)

// Valid indicates whether the value is a known member of the FilterOperand enum.
func (e FilterOperand) Valid() bool {
	switch e {
	case FilterOperandsIn:
		return true
	default:
		return false
	}
}

// Defines values for NginxConfigPayloadType.
const (
	NginxConfigPayloadInlineContent        NginxConfigPayloadType = "inline_content"
	NginxConfigPayloadInlineSecret         NginxConfigPayloadType = "inline_secret"
	NginxConfigPayloadManagedCertificate   NginxConfigPayloadType = "managed_certificate"
	NginxConfigPayloadManagedKey           NginxConfigPayloadType = "managed_key"
	NginxConfigPayloadNapLogProfile        NginxConfigPayloadType = "nap_log_profile"
	NginxConfigPayloadNapPolicyVersion     NginxConfigPayloadType = "nap_policy_version"
	NginxConfigPayloadUnmanagedCertificate NginxConfigPayloadType = "unmanaged_certificate"
)

// Valid indicates whether the value is a known member of the NginxConfigPayloadType enum.
func (e NginxConfigPayloadType) Valid() bool {
	switch e {
	case NginxConfigPayloadInlineContent:
		return true
	case NginxConfigPayloadInlineSecret:
		return true
	case NginxConfigPayloadManagedCertificate:
		return true
	case NginxConfigPayloadManagedKey:
		return true
	case NginxConfigPayloadNapLogProfile:
		return true
	case NginxConfigPayloadNapPolicyVersion:
		return true
	case NginxConfigPayloadUnmanagedCertificate:
		return true
	default:
		return false
	}
}

// Defines values for SortDirection.
const (
	Ascending  SortDirection = "Ascending"
	Descending SortDirection = "Descending"
)

// Valid indicates whether the value is a known member of the SortDirection enum.
func (e SortDirection) Valid() bool {
	switch e {
	case Ascending:
		return true
	case Descending:
		return true
	default:
		return false
	}
}

// CertificateContent Defines the PEM-formatted certificate content which includes the certificates and corresponding private key, all encoded in base64.
type CertificateContent struct {
	// PrivateKey Base64-encoded private key string for the leaf certificate, required only for certificate-key pairs to
	// verify the certificate's authenticity.
	PrivateKey *string `json:"private_key,omitempty"`

	// PublicCerts Base64-encoded PEM-formatted certificate information.
	// The `public_certs` field can include a leaf certificate along with its full chain of trust or a CA bundle.
	// For leaf certificates, the accompanying `private_key` is required to authenticate the certificate's validity.
	// CA bundles contain trusted CA certificates and may consist of certificates from different CA chains. A private
	// key should not be included in a CA bundle.
	PublicCerts string `json:"public_certs"`
}

// CertificateDisplayMetadata This represents the essential metadata of a public certificate.
type CertificateDisplayMetadata struct {
	// NotAfter The end of the validity period for the certificate.
	NotAfter time.Time `json:"not_after"`

	// NotBefore The start of the validity period for the certificate.
	NotBefore time.Time `json:"not_before"`

	// Status Status of the certificate:
	//   * `valid` - The certificate is currently valid and operational.
	//   * `expiring` -  The certificate will expire within the next 30 days. Consider renewing it to maintain uninterrupted service.
	//   * `expired` - The certificate is no longer valid. Immediate renewal is recommended to ensure secure connections.
	//   * `not_ready` - The certificate is not ready to be used, based on the start date of its validity period.
	Status CertificateStatus `json:"status"`

	// SubjectName DNS name that identifies the certificate. If DNS is not present in the SAN extension, this will be the common name.
	SubjectName string `json:"subject_name"`
}

// CertificateObjectID A globally unique identifier for the certificates.
type CertificateObjectID = objects.ID

// CertificateRequest Request structure for parsing or upserting certificates with an optional private key.
type CertificateRequest struct {
	// Content Defines the PEM-formatted certificate content which includes the certificates and corresponding private key, all encoded in base64.
	Content CertificateContent `json:"content"`

	// Name A name for the certificate, making it identifiable among others.
	Name *string `json:"name,omitempty"`
}

// CertificateStatus Status of the certificate:
//   - `valid` - The certificate is currently valid and operational.
//   - `expiring` -  The certificate will expire within the next 30 days. Consider renewing it to maintain uninterrupted service.
//   - `expired` - The certificate is no longer valid. Immediate renewal is recommended to ensure secure connections.
//   - `not_ready` - The certificate is not ready to be used, based on the start date of its validity period.
type CertificateStatus string

// ConfigPath The full path to the main NGINX configuration file. This corresponds to the `--conf-path` parameter used in the NGINX binary.
type ConfigPath = string

// DeploymentObjectID A globally unique identifier for the deployment.
type DeploymentObjectID = objects.ID

// DirectoryRequestWithFileContent Represents a directory and its contents, detailing the directory's full path, and the files within it.
type DirectoryRequestWithFileContent struct {
	// Files The list of files in the directory.
	Files []FileDataRequest `json:"files"`

	// Name The complete path of the directory.
	Name string `json:"name"`
}

// DirectoryWithFileContent Represents a directory and its contents, detailing the directory's full path, assigned permissions, last modified time, and the files within it.
type DirectoryWithFileContent struct {
	// Files The list of files in the directory.
	Files []FileData `json:"files"`

	// Mtime The date and time when the directory was last modified.
	Mtime *time.Time `json:"mtime,omitempty"`

	// Name The complete path of the directory.
	Name string `json:"name"`

	// Permissions The permissions for the directory.
	Permissions *string `json:"permissions,omitempty"`
}

// Error This object contains details about the errors that are returned when API requests fail.
type Error struct {
	// Detail Additional information about the error, if available.
	Detail *string `json:"detail,omitempty"`

	// Message The error message describing the problem.
	Message string `json:"message"`

	// RequestId The unique identifier of the API request that failed.
	RequestId string `json:"request_id"`

	// Timestamp The date and time (in UTC) when the error happened.
	Timestamp string `json:"timestamp"`
}

// Event An Event is a system message.
type Event struct {
	// AffectedObjectId A globally unique identifier.
	AffectedObjectId *ObjectID `json:"affected_object_id,omitempty"`

	// Hostname hostname of the affected instance, if any.
	Hostname *string `json:"hostname,omitempty"`

	// Message Details regarding the event.
	Message string `json:"message"`

	// ObjectId A globally unique identifier for a NGINX One system event.
	ObjectId EventObjectID `json:"object_id"`

	// Timestamp time of the event
	Timestamp time.Time `json:"timestamp"`

	// Type type of event, indication for affected object type.
	Type EventType `json:"type"`
}

// EventType type of event, indication for affected object type.
type EventType string

// EventObjectID A globally unique identifier for a NGINX One system event.
type EventObjectID = objects.ID

// EventsListResponse defines model for EventsListResponse.
type EventsListResponse struct {
	// Count The total number of results generated by the list or query operation, accounting for any filter(s).
	// This number can be greater than the number of returned resources when pagination is in effect and a page size limit (or maximum allowed) is reached.
	Count int `json:"count"`

	// Items An array of Event objects.
	Items []Event `json:"items"`

	// ItemsPerPage The number of items to display per page. This is disregarded when `paginated=false`.
	ItemsPerPage *int `json:"items_per_page,omitempty"`

	// StartIndex The first result's starting position in the list. This is disregarded when `paginated=false`.
	StartIndex *int `json:"start_index,omitempty"`

	// Total The absolute total number of the resource in the NGINX One Console, ignoring any filter(s).
	Total int `json:"total"`
}

// FileData Details about a file, including its path, content, size, and last modified time.
type FileData struct {
	// Contents The base64-encoded contents of the file.
	Contents []byte `json:"contents"`

	// Mtime Timestamp of the last modification made to the file.
	Mtime time.Time `json:"mtime"`

	// Name The file's relative path to the parent directory.
	Name string `json:"name"`

	// Size The size of the file, in bytes.
	Size int `json:"size"`
}

// FileDataRequest Details about a file, name, and content.
type FileDataRequest struct {
	// Contents The base64-encoded contents of the file.
	Contents *[]byte `json:"contents,omitempty"`

	// Name The file's relative path to the parent directory, absolute path also accepted.
	Name string `json:"name"`
}

// FilterNameCertificateDeployments Keywords for certificate deployment filters.
// When filtering on `association_type`, only the following `filter_values` are supported:
//   - instance
//   - config_sync_group
//
// When filtering on `deployment_status`, only the following `filter_values` are supported:
//   - latest
//   - stale
type FilterNameCertificateDeployments string

// FilterNameEvents Keywords for events filters.
type FilterNameEvents string

// FilterOperand defines model for FilterOperand.
type FilterOperand string

// FilterOperands defines model for FilterOperands.
type FilterOperands = []FilterOperand

// NGINXaasUserObjectID A globally unique identifier for the NaaS user.
type NGINXaasUserObjectID = objects.ID

// NginxConfigDirective defines model for NginxConfigDirective.
type NginxConfigDirective = xp.Directive

// NginxConfigDirectives defines model for NginxConfigDirectives.
type NginxConfigDirectives = xp.Directives

// NginxConfigObject Details of an NGINX configuration, the main configuration path, and the configuration directories.
type NginxConfigObject struct {
	// Aux An array of auxiliary directory contents related to the NGINX configuration.
	Aux *[]DirectoryWithFileContent `json:"aux,omitempty"`

	// ConfPath The full path to the main NGINX configuration file. This corresponds to the `--conf-path` parameter used in the NGINX binary.
	ConfPath ConfigPath `json:"conf_path"`

	// ConfigVersion A hash that uniquely identifies the contents of the config object. Can be used to detect change when updating the NginxConfig.
	ConfigVersion *string `json:"config_version,omitempty"`

	// Configs An array of directories containing NGINX configuration files.
	Configs []DirectoryWithFileContent `json:"configs"`
}

// NginxConfigObjectID A globally unique identifier for the NGINX Config object.
type NginxConfigObjectID = objects.ID

// NginxConfigObjectRequest Details of an NGINX configuration, the main configuration path, and the configuration directories.
type NginxConfigObjectRequest struct {
	// Aux An array of auxiliary directory contents related to the NGINX configuration. When auxiliary contents are
	// provided, they become the authoritative source of non-NGINX configuration content. Please ensure the
	// provided contents are complete, missing files that are referenced in the NGINX configuration can cause
	// NGINX reload failure. When not provided, the previous known auxiliary contents will be used as part of
	// publish.
	Aux *[]DirectoryRequestWithFileContent `json:"aux,omitempty"`

	// ConfPath The full path to the main NGINX configuration file. This corresponds to the `--conf-path` parameter used in the NGINX binary.
	ConfPath *ConfigPath `json:"conf_path,omitempty"`

	// ConfigVersion A hash that uniquely identifies the contents of the config object. Can be used to detect change when updating the NginxConfig.
	ConfigVersion *string `json:"config_version,omitempty"`

	// Configs An array of directories containing NGINX configuration files.
	Configs []DirectoryRequestWithFileContent `json:"configs"`
}

// NginxConfigPayload Details of Aux File Payload that goes with an NGINX configuration. Provide hints for the backend system on
// additional file contents that should be part of the NGINX Config Publication.
// Can be used to deploy files related to SSL certificates, WAF policies and WAF log profiles to a data plane instance.
type NginxConfigPayload struct {
	// Contents The base64-encoded contents of the file.
	Contents *NginxConfigPayloadContents `json:"contents,omitempty"`

	// ObjectId A globally unique identifier for the valid payload object reference.
	ObjectId *PayloadObjectID        `json:"object_id,omitempty"`
	Paths    NginxConfigPayloadPaths `json:"paths"`

	// Type Types of Aux File Payload:
	//   - inline_secret     - indicates the provided content for the payload should be stored in a secret location, and removed after the publication is done.
	//   - inline_content    - indicates the provided content for the payload should be stored, and removed after the publication is done. Note, the contents may end up in the `aux` content if used in this NGINX configuration.
	//   - unmanaged_certificate - indicates certificate content for an unmanaged certificate detected from a data plane instance through NGINX configurations. Will be filtered and ignored in the payload deployment.
	//   - managed_certificate - indicates public certificates managed by NGINX One Console.
	//   - managed_key - indicates a private key managed by NGINX One Console.
	//   - nap_policy_version - indicates a version of WAF policy managed by NGINX One Console.
	//   - nap_log_profile - indicates a WAF log profile managed by NGINX One Console.
	Type NginxConfigPayloadType `json:"type"`
}

// NginxConfigPayloadType Types of Aux File Payload:
//   - inline_secret     - indicates the provided content for the payload should be stored in a secret location, and removed after the publication is done.
//   - inline_content    - indicates the provided content for the payload should be stored, and removed after the publication is done. Note, the contents may end up in the `aux` content if used in this NGINX configuration.
//   - unmanaged_certificate - indicates certificate content for an unmanaged certificate detected from a data plane instance through NGINX configurations. Will be filtered and ignored in the payload deployment.
//   - managed_certificate - indicates public certificates managed by NGINX One Console.
//   - managed_key - indicates a private key managed by NGINX One Console.
//   - nap_policy_version - indicates a version of WAF policy managed by NGINX One Console.
//   - nap_log_profile - indicates a WAF log profile managed by NGINX One Console.
type NginxConfigPayloadType string

// NginxConfigPayloadContents The base64-encoded contents of the file.
type NginxConfigPayloadContents = string

// NginxConfigPayloadPaths defines model for NginxConfigPayloadPaths.
type NginxConfigPayloadPaths = []string

// NginxConfigPayloads An array of payloads that define which objects should be deployed and the file paths where each object will be placed on the data plane instance.
// * When the type is `managed_certificate`, `managed_key`, `nap_policy_version`, or `nap_log_profile`, you must specify an `object_id`.
// The `object_id` must refer to a managed object.
// * The NGINX One Console manages deployed file paths only for managed certificates and keys. If you don't want
// them to be managed by NGINX One Console, `inline_content` and `inline_secret` can be used for certificates or
// keys respectively, with `contents`. When you retrieve certificate deployment details,
// only the file paths of managed certificates and keys will be shown.
// * If you use `inline_content` and `inline_secret` in your NGINX configuration, the NGINX One Console
// will detect them. When they are used as SSL directives of the NGINX configuration
// for certificates and keys, the certificates will be listed as `unmanaged_certificate` in the certificate
// deployment details.
type NginxConfigPayloads = []NginxConfigPayload

// NginxaasDescription Description of a resource.
type NginxaasDescription = string

// NginxaasNginxConfigObjectID A globally unique identifier for the NGINX config.
type NginxaasNginxConfigObjectID = objects.ID

// NginxaasNginxConfigVersionObjectID NGINX config version object id
type NginxaasNginxConfigVersionObjectID = objects.ID

// NginxaasOrganizationID NGINXaaS organization id
type NginxaasOrganizationID = objects.ID

// ObjectID A globally unique identifier.
type ObjectID = objects.ID

// PaginationResponse Outlines pagination details for list responses, including total results, start index, and items per page.
type PaginationResponse struct {
	// Count The total number of results generated by the list or query operation, accounting for any filter(s).
	// This number can be greater than the number of returned resources when pagination is in effect and a page size limit (or maximum allowed) is reached.
	Count int `json:"count"`

	// ItemsPerPage The number of items to display per page. This is disregarded when `paginated=false`.
	ItemsPerPage *int `json:"items_per_page,omitempty"`

	// StartIndex The first result's starting position in the list. This is disregarded when `paginated=false`.
	StartIndex *int `json:"start_index,omitempty"`

	// Total The absolute total number of the resource in the NGINX One Console, ignoring any filter(s).
	Total int `json:"total"`
}

// ParsedNginxConfig defines model for ParsedNginxConfig.
type ParsedNginxConfig struct {
	// File NGINX Instance configuration file, corresponds to the conf-path.
	File   string                `json:"file"`
	Parsed NginxConfigDirectives `json:"parsed"`
}

// PayloadObjectID A globally unique identifier for the valid payload object reference.
type PayloadObjectID = objects.ID

// PrivateKeyMetadata Metadata for a private key.
type PrivateKeyMetadata struct {
	// EncryptionAlgorithm The encryption algorithm used for the private key.
	EncryptionAlgorithm *string `json:"encryption_algorithm,omitempty"`

	// KeySize Size of the private key in bits.
	KeySize *int64 `json:"key_size,omitempty"`
}

// CertificateParamObjectID A globally unique identifier for the certificates.
type CertificateParamObjectID = CertificateObjectID

// EventParamObjectID A globally unique identifier for a NGINX One system event.
type EventParamObjectID = EventObjectID

// FilterFieldCertificateDeployments defines model for FilterFieldCertificateDeployments.
type FilterFieldCertificateDeployments = []FilterNameCertificateDeployments

// FilterFieldEvents defines model for FilterFieldEvents.
type FilterFieldEvents = []FilterNameEvents

// FilterValues defines model for FilterValues.
type FilterValues = []string

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// Paginated defines model for Paginated.
type Paginated = bool

// SortDirection defines model for SortDirection.
type SortDirection string

// SortNameCertificateDeployments defines model for SortNameCertificateDeployments.
type SortNameCertificateDeployments = []string

// SortNameCertificates defines model for SortNameCertificates.
type SortNameCertificates = []string

// Conflict This object contains details about the errors that are returned when API requests fail.
type Conflict = Error

// Forbidden This object contains details about the errors that are returned when API requests fail.
type Forbidden = Error

// InternalServerErr This object contains details about the errors that are returned when API requests fail.
type InternalServerErr = Error

// InvalidRequest This object contains details about the errors that are returned when API requests fail.
type InvalidRequest = Error

// NotFound This object contains details about the errors that are returned when API requests fail.
type NotFound = Error

// Unauthorized This object contains details about the errors that are returned when API requests fail.
type Unauthorized = Error

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L37c+K6+TD+r3j4fmfafkqytoHdJe98fggQGwg4iwEb3PRNZFtggyx7fQFMu//7O5IvGDAJyTntnM60",
	"05xNbOnRc9Nzkyz9o2K4judiiMOgcvePigd84MAQ+vSvNvRDe2EbIIQ/yIsnfQWNsNch70wYGL7thbaL",
	"K3eVe2aJXB0gFDMRtn9GkLFNiEln6DML12dCCzLGAdztM65UKzbp6oHQqlQrGDiwclcptMlHq1Z8+DOy",
	"fWhW7kI/gtVKYFjQAQSN/9+Hi8pd5f/7cqDjS/I2+NIugfXrV7XysIE4/K0EAcxAAuciJfTtb6bh4QgK",
	"wV6wUQh9wYbILBDYgR5yYyeT4zExSRfGpX8HFP0Cnxnz0Pf/MFEATcbGjOHiVYQN0oPZ2qHFuKFFSE9A",
	"HfSEscDGxksq4AA4kAG+D2IGQbwMrQJzfkbQjw/cSeC8LAgZQaXIDTuETvAeWxKKJODACzz4Va2EsUdG",
	"ovicco6ytYRT9zjF310wQejbeBkwNjYJeELk1rINi0mQZkI344YeM38mTIU74HgIVplXyw1CQulrlXl1",
	"qfRebPP1L7fMxLKDA/eYreuvg1J2v6Yc2gAUweCVAdjMn7le8PpvYG3KpMusfPKgD7B5JR9NuLBxpipu",
	"2pUqY4KxjZdVwlQdXlbC1yPijrmScur2Gd8jVKKoThSERFsh44DQsAgmRV0Nbpl25PsQhyiuJjhiFDNB",
	"5HmuH0IzQ5mxA+b1udKTnivvC8H1jiXwPuNznh7YrFDCrmOy4eIQHNi8hvHW9U/ZfPuMhxEKbQ8VWhgA",
	"E9YbFrAxNJkoyGC8/vOVPPWBEUL/9hk/4CDyIRMeafKfgiNmJiyGARNabgAJgm9JjugzxRAuFtAI7Q08",
	"wnViQSZ0Q4Ay4O6CIpaKOCGdCSw3QiaD3ZCBOwNCk+FYvn7APHhXWIkClc+YdGpX7iq0FfdP+g+f/FOr",
	"VCsO2A0odpU7Mm614tg4f5DPoATX0ik1sB07LBWyjUO4hMSHgpAJPGgQLxRQFjhgZzuRw+DI0YmFXzAU",
	"43Qa+TCMfAzN22c8hmGYCNSmb1/ZV2ZrI8T4MIhQSCYbdtPOOiQts85VRo9CBqQSMNwIh0nPICT/1SHj",
	"+e7GNukwJ+bNDqg8gOch2wA6goy9YF49sLQxCKH5SufSAqAAvjGVEGVMUSqOjQnVlTs252PKI8rJp8Ui",
	"gB9mZRACn7LIcwObWpxUzRIOBdVDCxAyr9zrv4hcN8G+lF6ulN4f2QBlYYzuuggCXPRi9hFd2cShgoQB",
	"xMTWgYABTI44g+wgvGU6cAFoD6I/JIghVKgWxEwAQ/owoY0BuV66C6bGsmw+FvCPtPICC/KBj7hgJsNn",
	"8VPKiJQ+yoix64cd24dGQv0pM8hrQr+ZNTlEpr5NrA2gVunAG9LYcBFKW+eIH3GCjAGxmTKWyD/Tqzco",
	"DFw/fDFt/4hAiImM/1a5zwBWqpVODr3y91MrUq3sbkifmw3wCdyAdAaFzmahc8afN2KmUoZdihRJ0EMG",
	"hz55Qc3gn4O/3DJPvmljgA6zyCRTw7ExDBjPtx3gx1UmgIaLTforDI132PRWIJOxjLa/jkEUJvnrpUDZ",
	"S4GylwRYmY0uYeAVbPsj8qpaCaIkLk3/xG74osOF62d/gEUI/d/C0yADfeHtCQKXYBTxeqNNiu651H6R",
	"1CvwXBwksmq7eIFsg/oHEi1BTH9NjTYRw5dVkJiPK1M033f9ZKBjPZDhzwgGeehIJWwATEwEMbbQX7i+",
	"Q4xtmLpl24G3JDYQXF+3TRPifz2OE2rszvG0aciYYEFx6uEQ+higMfQ30H/w/X89bveYiTDcedAguEHS",
	"jHENgwTpJuPixGtTdG6ZHwiCADKhH6f2m5LEgCWwMYMAiVwTKjYA2WYqmX+bChTF7rsGDEh+Y0YkrGXs",
	"BCXGxl4UMm4xZbllFOjbi2OSiNKAkHqqLPBiTBACSp/khoIbYfPfqdw+DNzINyCzBUn8syAYUHSmGESh",
	"5fr2Hv4bUGojG+Iwj8LykQmX09lW5GRR32+peU9HOCl9tQ9IH4/XIQltGj3+eBjeJJIhcIs+M6U5rR3Y",
	"2ECRmXY68hFEoIbrJ7aKhhOeb28IhDWMqwxAiIHYcM0kM9ZBAL/WE2+Q5yb/qHiRjmyDWsegcleZrpWH",
	"0VSaytPR/xJ5eD6hOLQTS5jCf1nD+Jy4Fh3gJhuygEuWcGXBE4JgUSSlymSlriSDPik33RAQHrB9Ej09",
	"481BwwuNSDoZhRbEoW3YYZzQmfCXxHwUt+Okq8bVG9/47yWZ1jFP3qHzshxtnDwn2pLkpK9FyK9JWYim",
	"0amQGXDGGwYgFy+TWoYdBswiQihJuWm24UcBNQGAad8zeoRNBG+fseD6Z4CCpEQBDDJBAI6JQF4LAqW5",
	"Ri6H0D2wk2Bxzm1qgxJO50Pn1YQEMWgSrM501gExaRfYBPVjHJmF7zqMaS8W0CdTgHQntAa3zH2mUc+Y",
	"qtQheddhxj+q6Mes+KwW/CrWX/92rBKHECep1BGdKUbIduAhEA9hCIiZPdcgmgT6ME2ekplNLDwObYAY",
	"J+1HeAOYZOCjSvjxBD6EMncVnuXrN+z3G64+4b7eNZp3XEM7jtRomxptwx61CUIQRkFSrbDN02jvrhJA",
	"tHgxwEtgLzE0z01DAY1/lEQMEJtZdpwpDrGwtmuWFvuLJBKMmzccf8M3JmzzjuPvarVbluW0omhNYidI",
	"OFQpmc9F+suQo2n6b0GvdsN+veH4T6KXsf7qtYlx0uHXqZDO3I00ZsibpHiRL0ecuZJbprdgSOPUEaaK",
	"SSYTaTm+lxi4CyEObBdXk8hzm1ZyKCTXcVxMRzpxL5Xtdnub/nVruE7lvWl2GuEnhF6Ra5ROxN9v9Sm4",
	"LUozr89XqhWP2H2fwPy/pP3L7f9UyhKgpXtzhGlwS5d48hc3tuO5Pg0ZsqpO0i4ZwqrcVZZ2iIBO2Phl",
	"0fiClzbefXEx/BIAEHwhdtd30Y2HAIZfvPXyy6EMEXzJYP065k8hqC0PQoPQj4ww8iHliQd8WuJ1fSby",
	"ApiURo6sN/VSAKfrRiRPPQQBZ5FHIbQ7iisqlep7UUm2YJYAuzHATWLvz81SYZArJ1cWvOXDnOsOnVMl",
	"WlJlHLCmZZ3DbKNFPeAQH07Xw6gmFUu/xPe8Wfk9mSIZRe/o/jg3KielBvo8M3YF5O+eMcP8D/NK7d8r",
	"c8NMjt8T42Bkyx2JlaTePI+IAbpNQcCdZxPcCZQzMNRy0BaQ6ktqZDDchUyNZUwQB7dMm4QHJvQZH2K4",
	"TVkauowD7CS+iLBN0ks/8kiUQXI624BH48NLRGCXISEV9BMibpme40DTJm/paAAlkRAxaxCbSTAEkyWM",
	"ABrkH8PFOJ1b2ZjEKPkQmPHFUUOGvi8sWFVpUH7ITKkbIq4iKcsHp74onUJpVSZz1Bm3s19pETRH58p6",
	"TLGylVjdlwx+yavCkJfewgtdC4gRhXXxwl7+oAauzDPTaJfYP8K1ZPnCxowk9qQZEcLCXkZp+WFhI5gu",
	"lh5yoiDr9npzQ5rfEFCvhfp7tmxI2iRQdRsD/9RYVb7A0EhNLv3vLYF2PJHrbPPru2s4h+Lpb/RNh+rj",
	"NZ6JtP7je6akEO/6cep+VDu0BBtdTqflQwgN0hq968fUKpHZk1rKoMqYMAQ2ypYn85Z/Cg4KVs0r+UST",
	"gsw02ZS/xz6FNijXV5TmNAmMVLHy8Qioa1fUYQeEIHPQZzXKS75pkoRjHoIhTOZNauiPcPiIu0kjsYTm",
	"Mp+TS+3fLa4gSUWIbXTsgMSmQZVBIAgZxzXpagqtj/4hBVsmUYfmB6WjU59AybAdyGwteDI+LaQdkX57",
	"fXL0GxTpvHJykEU5zEKDgy17A+RHtTEp9ZVn3EmrrEQRpGoWMEB3ozBJwknvIEmXiguPCcvvf/SySmDA",
	"LICNzjUoAVli003TTkPiQlXodOQqYy8YsAE2IlFjKYMdGARgeUFgScE7bcIk7/VsGnm+qyPolEJNqSJ+",
	"oxTwuR9KtaHAkoRrhC2J9p3vX7AdGITA8a7R8T/bmJlO2n85KHtCnAU8D+LSEU5UJePUEXVFLErVZ1Nq",
	"ue4xQ9+QQA4wQRyE0Mn4fFKOAXRDCjRfDq74rmLjIHy5iTZyTeAnI9Hhvq8w+qZ7QNxWCjKt2N4N9429",
	"ZW85xoRk6pkMTXQZIk+iKmlNwl0wNcZyIz+zeAGEmMkqO+y3Cdu8a3y7q329Zb9//9b49u1rXatUK0WU",
	"6GbDyzgVhJVWlfgbtn4Bbr7DIAgBNuCLgSDAkXeejZUx522DedjIWK1kW+TO5ZO9ydQyG4fJUEpmFo4/",
	"Nqc6qYHw4RL4ZjaRkk2cR+FhLx2Gea6Y0HFvuOdKLkA9zrFgUsakQn2uRDif7c8Vag/5RiLXUkSv5trJ",
	"HtA35x6dbinfKGknxS2u+aZOXedkkgdnQ8ceHZoOW803nKTbLHIhpnabtL4t5D9n6naUbwR5FYFCpEUk",
	"4L0QZtmIPnpZuXpwZXqUzBbS8KVk2MLbEwwKb06QKbwpx+vUnlEsi5KsHkX7mRJftGq/Zedymhs9YZgZ",
	"v3wSvJd6JHT+4XOPZOfqwA5COV36p/YKoadF5e5vb8+2dDeV7eK876/qKZMHaQCZDHQeOeTh4+Udm4kL",
	"yjh1bciZuLSyvSlF7UpAnSvP35M9pUnQetFAJnEMoNFxNV2MSYo2QRqtp8F9lQnsfRqSn4fq51zJcoLy",
	"kEE/XonLGhd2e8IjFdXjEF67BngpGs+mXzZIgYrUdjnAhFnd4QyFT4biBM6fiCMiJmIDj0oiHqBLZccZ",
	"3gfrEkQqF9ZG7D0sMrRK15LjtCResrewJFzPpZgOlHG3zFadpr5X6hwZqZquiNPB/ki69PvItcoAPXBR",
	"lCVkAAUuAwwDemESD39M6GWiuiCQtz+cOCPssbiFvHwzYLoTO8i2g+abtxkXM68gCFzDTpwhwee1muwL",
	"oIJwEXJpRfjsewcfHvbep9XszFknfyUVw5cgxsbL0ncjr3T0A5ZpzfLzwyMSBoTJ70EIEDwq4Kaz45Ra",
	"ug3zBIUrw5QUpff3KlavalqC2TXdSrA/0qNLn9Ic6Q2NG4KCnhQYdwg1Ps6WBG4hAfn76ccpxZ2PPelj",
	"Q2QfqbzY+Bxw8MEvajJ8SmpFNB4DIJgG0P+NlWQJgDETBdC/JpqLAv+PH8tJpGOyspDu7d4kW52Oc1F/",
	"eSyQdz64qFZ05Brr90RXNjhdqk+Wk8LSkcwimmdviZMofZFtDSsjI3fJ53QgG8Oylice4YBU2qWa8OzM",
	"SRxLf+fddgo935D/zjsSvRUloqdyt3G63kK6G74bBFTuF+V7/dwq1Y5TLl0mKfiX05TM58uBj7tgQOka",
	"WPWwQna8Nna8vnH8LgsvbBicrdCDaFe5+9vfaQC3eEmpurQUloANaLaUFtL/Vgy6Km2Hs4z2/dqc9b1e",
	"Ww7ns9ZWU+WFwSux6aCVNm59a9v3y167tdZUzTLVHdsTlKfJVJiOWEuQO8Fjr03e9/86s5uWIa435uph",
	"oztCqM2k7VyVkBE3DTMONkBt7E1RiOa8su9RmMlP8flgJvHz/fUwNVFg52Nuq4tCpI05X5shChvwSsOI",
	"ub3pDFP87+0Fqm/ms5Y3qM13A75h6aqyN0Rhpc2Gm1nX8Ac8t9EdxOq1np3hRn/E/Hlo1LTV09Zrtpce",
	"Z3Ql1nAUSx+3PB1L7FxtEFi0Ta+b0tCVkIE1ZNjnbZ5Wy+1T5/5bG7OPbaxsjZoca6oQ9sQQwctwKI0J",
	"n9z6sLPeluCzns9kyxB3lu5Mw3lNjvV2Lse9Nuvz2qy3pLybtYK52kADlfTdfn3q3NeHneBxMXIfzVlr",
	"b3b7aK6yS11tRmAmbwyb8nQJty7lTaInSnzGo4u0ccjs9r15bRgCtYG1mcSW0BhqMzkGqrQfqCjSeGVv",
	"dgity4zWnIYMD11Ee1NUol5nWX/qLE9o7S+o7oxbi6e0PejKrNHpLXW+/q29TGnp9jewixaGKOwNrhlr",
	"M4Ej+M14C81VGRl4mLRPYMfazIzBTEa9dh8OeGELxt9d3TE9HS83Ot9Ai+589zj+7g5s1+u3e8teQZf7",
	"nZ7dE/uEJ/5TTkNzNZ/Jns7Xlwm8Jj8cf89pTHQROb32cq2rwtYQlfWsRnnmzfnp8sf43lamDWmkyJ3x",
	"g/LQs9fHfdsZ3jJnOPWl1Llne23zW89RYsNpxk/2vT1xmmxP1Dam2lj3MIufiv277GMBztZwmnWoNLfz",
	"mbTPeWS35gNF2+hdwq++NZgKW6CatYEiI90RIjO3F+cweqLFmt37r4P4exl9Gd+bmbx6cQtPUauT6g3l",
	"geY0454oW6YoZDZhZXb7Qdo30HnJMkW00e37jbaaRqm8orlqIh2PIoOX/cFa2ugqZ+kOpSezH/RHq/W3",
	"c66513nJ12byAvAKMkQhADMN9cRmdMQv0YwNUVqQOakJTRaoHNJrCtvrKGFpO16J3m4nBUBVIlNo2jov",
	"N2Y12dNVZWPORsvhpFUOk+hy3MIGbq2e7O+bkjn/Ab7mc3eZzV2gNqOP8TaDIU3I3ASqhPL5n+gExXVW",
	"kzZzPkSm0PQ1VdnO1Z1nOtPC/DuSB5lH6yI/JJUtlZumNt5sN+d3nqY22Bnf32hdtDBFFGpqkzPb97uh",
	"eKktZ8FcJpIHnely2CmjqWUZtWGCy97dDPhzW5jJcDEids5d9bqtWK9ZjV5X3vS6squNW+FcbVgar4Rk",
	"7Nxm4uFjboszfoo7z6jJSLfvd9LkfpvjlPVBzWiucqgnfM/oWvW6yl4bt9aJfveW8kNjcrB30kbvEvt8",
	"vxuujGjYrm8Hq4ddr6tZuojWPybDrbEPHnNYImeZouT22t+/5/HEpL75IXJYn42WRBaG2PR0PPrruQ61",
	"/jqzv7sqV9/MxoE3iJfRY7xen+jKRfsxnLgJze3v6+Eqo5t9LNPVE5iWJsoLICqWJipxr93v6HyDJbwe",
	"KHLDEKd2r91ntZnFDniL1dWtfWwj+8jsKrFu38fDzv2yt9ptf6yFFYltjLjFAnG61FUhmRNkLhf8sc7P",
	"l3O10SjOO5NHLGi3lOl6tyfyBMTOi9JGE6d/TXwY0aPdZs4LARCbxE9mdDt6d/RtyipjZY06stJ8Gk05",
	"oe+Y7FPczP3rj3ZzpfMy+rHaboxO3T7Wv//937wseFfhmt/YG5a7YbkJy97R/2uH7xbTz3qzwDOpXXLN",
	"Ov/r73mbQpRKmt2atCRfHpdiZU940hMbGKiN+tPWq+m1vk98OfHTlJ8kjmy3LHMmb5627qM268d6rb/Q",
	"xSbute83piPEhDda3Iw0HkWw3SQ+aWPYjUDnjaXuEFsroaettwXqqOAjm/x81tsYWIkGfDL+ALc8rRM8",
	"tpceMh0lMruHGMjkmzHglXjGSxvdaaA5sS98Y98jNqPTY5OYxX2k8jrEYZ7uSIGpkvghHxeZ4nCTxxAq",
	"CrVxg4WzFjKymFiUkeYInN6VF2YXbbXx/ZLE7LqIsthho/MSq81GYRZzEd6k9mCjcU1Hr/XD+WxE4loL",
	"qPVlr22sDUcJ9ZqMZryw1rq95WB8f3hWS2ShxjL1TbNU32bje7vf7SNjpiCjNrJ7bePxONY4/THWRk22",
	"zC6Rm5zYS77fMEVlT/y8jkfLni27Zlfezmp9pDlKrM1618C1+3TutxbmTCJ2jdjHyKQxVwbPWhAfZvJC",
	"rJG4gtc2ht3DB96kc5RrUt3IdIDoUq4DfDaPE/1J+XeIH4n/FjVPF6cFP1yICWryyhCakV5rcQa/LL5P",
	"cQiRNmsRW8prSiEOaN/z0uRgV7Wa5xkkXizErkBtrPSustbG9xttJq8OOBOdnEda+/vPgUN/pzH51fP6",
	"KJ1MZvXX+ncyb49mK7GMyv4QycsIdkcb0JVD/U3JXfppuabIBcSi6+PWnsLpHMOe16R973OwV0Ytywpb",
	"iSWvWZ/E834JRS7IswqVszR+utF4EqV/Ap5oelrmrUQUEi8x4L2tphqfofOnISq4J3pbLbceJKreeXNe",
	"oJHbgPcs0xH281rfM7qj62BehCWwOs/6hB9X4meZYjOPWk+tmIGl/eNH5NLt7w/RRypXnkQgn5Otrh7k",
	"aopK3Ww3SUbh6fYn5NqV6+aJ/ppOYz3AEqfbjZ9Dh0MDR9gabW6tzaSV4aCtKTbjSzKYq6MT/dUird2o",
	"zWf3kclfy//71Hud0VkfqNJGn7U2OvF0H9Jfi50fZODpqoC1cdMync/Nh/lMO58PtVakxZ+a91vdMb6d",
	"4LY3HeMDOnv4MWoa7nUlXqu5pzBZoGqfotck2X1X9jRipY9h8rozikxe2A6waeuzj8i3HxqdUx6aaI4/",
	"xcOapva3p/YOtjlvzjejj9s7tNL3p7gtQ+A08GfsXYl86wOV2w/Ufmh8VPccbnvwzNpGx6ONyTcdzf4c",
	"33ReczK+aU4zMttN+mz4KXtibjRnHheilxK7/hDOZ/0VINHE+H3ezWe9JYmOeqJiGauL/mKv8/WP+SD+",
	"EAGdRaqqsBqofU93LAQ7o+0V9mUHO5dw4/YkEteux22t83kcYBndVgDULCtsbjVx/jF7IMrORV9GMrNu",
	"atevkm9r3xOVrRG3LDC5QG+tz35MF1uxKc4v0UvtS4L3NNJnLaTVlPgtv6lPJO7pkiwSf4R1vol1cRpq",
	"qhCb4jICPBeU+/SWr6vbN3HT+OZG43dooCqWgWV34IQhvEA/4Lmvl2RB/a5DbIJSn/PK+3a/awUXY56E",
	"ztCIOUfnG6zO939qqsS+IQOk10Zv0qnPhqEhNmvarL/VefSm/zW6LfZtOpuWwaP9wGluNbWx1nmJS6oO",
	"DWw4whaIaGXEeaay1t6mczOfSZ4RNzaGSDKd5sokGQoeRQbJAknGJSbte+3WRuvev00nL+zBbEiyIaQ7",
	"8mZeSypaAyxtacW0K7maSrOfpc7L+0/SSeOjYxvSXJtv6y2lj8QEJGPUVYE1Ym6jOZo355UibILnnuCc",
	"4NII9bNn9cfeJ/OK09jF6Mr1d3hAaK/r6i7N8OX9QG06moNWmnqZv7q6jQzeQtps9HvhWte70u+Eq7kx",
	"HHlrOM2VNpP2QG1ggm9B934vnIlc38YZm5bRbtR0dbe6wj+HunjRt9TmMyn8WIwu7PWLfmAZSjU3nPPN",
	"kM7DmoTe8YE1uLoMa843Vzr/cHUuPee/X6KzPlBP4xBu/VZsDBwh1kTkaG/gBxyBn4+5n7qz2w7Uk2pL",
	"aUy4216SK2xz4VwNie0KrvKl3T6nv4GbIb7tM8/yEfIzeQseCvTa6Hob4QxJHGK/QW88n/Wu15Vu/3Is",
	"SPBzlDUQBXYwa1lzPiS5QJhVtw37PP4w8hWUEl2ZSWg+/kC8xSvWG3TugdhcgZppmc401JydlVfcSumU",
	"am/pnFGTOWL/r8uFW3swG71Bp7zSP5QTSkGvK/tv0FqXJveNgSpZA1VCBn5HX0S6qrnVVHY5r/XZt+Aa",
	"IoqMmmzp4vaKuWFtL8eqFq3nXV/PadWPan7n8PaGOP9Iralu1FoX43PooO3H8i/PIzn1BRlv5jUZmW0u",
	"3z3xfq6Jop6o1OnKm3gxDv4wXE1ULtqC01WC93MvObxcR2yuTFFhB7NsB8q78vAM/vsSqBz+/fDj9mDc",
	"Co3a/VKfSYVVD4HTRLQZ8JynievPxAYhUEdLXUVrMG7581kvl4+pyp4eN0NaZ/1MjXF2X4hrlTVQv290",
	"3sSfqx03cUE+Cc21ZahPZOszNEviwymd9cGM6N0u/fsDttp5yFcqTAetNfX7ZsibW+MzdHYkbHTvl6R/",
	"XrdMYeqz+9hsf6o+uy+BxX5ODtxWymu9mqeJCtG9z9bwE90SuUMNP4NZEzigSj7doTD+GEy9ltcBeKDK",
	"SI+bNU3th5+qWfKKnccwOW5L4nP5T9Dr6N0z3OoDlWXNT9TJ9InMn8qVxHy6Y3xGrtG5DJYhydfnM+mD",
	"9d6WZdSWS9KvDD8j5mr6bP7RmmBorsrwk1I+fgw/01l/bKXQsR14G8YezD8pumvU6s3S9f/kG7aTvd/R",
	"7u1P7UC0s5EN/LhwxkL+SRD9Wic5FuhwbszRrtqrP867eHhGybbtwibcdw6zOhyq8yvbl/uygX5Qesb5",
	"PWOBwEq+3k++EkDx2VlxJ19DJTDTTxFvmXZyEQQ9TIeebx7ScxYsgJfpaRWRZ4Iw+4C6sNc52XJ8trE9",
	"30v8lowKO5eLl1hcOhwo+BcI5fxorlRCBxLKPqk62+z9+Y83KLHtI3Fc8RkHNv6jvuJImPTuF4H/4o3x",
	"/2YTwtBP0w5Q8r7Ah884O8iZkhYzOjRcJzmNMT3FOEw+KEwPWnYXDHbxTdncyL6XzA7EhtllLYVRjgbP",
	"z4WpMvQoF7xMT8UpHJtCj281Ts/WOhkYkJ8ogM84ee1D5AKTHiES+TBlQHIeZYFYxvPhxnajgFljd1vK",
	"oexwSmqQAL1vI2TcxTOm3+AH2SVTH7IFF86k+q+d/gPY6WtlU2KurzDRP0BM9PJNu3Mf7RgyNJM2TsS0",
	"dAtnYpbO8R+JZjOWTT92TK26Dow1xGZ21oKLnzE4HCBEmHSQdHIvzeFClsJJtkfO4cfh+InbZ3ymCR5y",
	"43QaF2zTeDw4OUJavRcYz0W2YaeHOZMHyF2SOZpaAZcB9Hh5htr4/BPcS+d/BpW7ymDMhoMx15anZn9i",
	"tzqy0p+Op1p/xApTmb5jw/aa64+n8lR5kDoj1ZtprFAbT/stjUWKsjZiww5tc7rdyuvvtSknKHAauspa",
	"mki1eSx3Nc1kZVmdegOd8/qgq60ma0GWp9vHERJaJtv4KSuSNFoL3dFEUOSpUDNZz5b36KeqmHWd7+0n",
	"q5Y0XXM1WRE0WdDk6TR8GM1aP6arVjDhzM5o7dn6lOMmirA3t15nqqAHBQmyzCq1MdIUuBaQjI0tnDYe",
	"RpOWBBBqTKayAh8aD7IjiOa+1Zis5dbwgfs5ryFJFpT6ZC2L8yn3oM4sAawFub3u4wnS2qMpJ404s26i",
	"dSxjyZL36Kv2IAvKA+Vha6gowog3a2NO9rUHb6qLJp5yBgfWu5/ydCeN1DCls+9OpsNHBWmSyZtYVpE0",
	"mrS6I07ayZzUn6+kh+lUaY8UQRlNH9jxtP9gskJN401hzAobwv/pdBjrrNBXps3ucL0Th4IiGsgbwpHX",
	"AKqlyauWpq7M+UQV5hrW6qbaH84VTTOnZl9aobnECSN52g+nM49/mpmuyTfAdB12pg+7jtZV2pLI1ues",
	"WxvVWiLEcreNzB9zRRjqjrRTlPu6LEw50EUjKLTGuqNNTUFoGVPTHnb6ssbJymg250Zrrz8UNAuKVtvA",
	"EoCOyT7ul/GwprmTiTaZdo3HoWiODU7SZCR4j3ulo6rN4VDVpLFqWmNW4mW7uddE1DC6mjBi+x1N0eKJ",
	"qgka64ljpd8aceuNKbT25kOwmax328c9csDW87SaJQzRfGcg0x2L5kZ2LE12GvM5Vn4Oebk37PYHwG52",
	"FDRsAKwNh+vmRp6gDcTDxnAtK4M4jMdi/ysU5NoIm8po1dq3HeXHmLd+zHmTNx6keKKg8VTdTafIclSl",
	"7yisNJD4ET9cc325tt6AlbFROMWGHeFpvkf14aq/n9phbCoy0tY7LE/ueUldPg6R2dHWAp5M+63R1Pyp",
	"zLz2dM21hw9Up9ayaMoK229PsYaBs96pqBVrSGkNsYxUJA+n4gNrrtDe7AozsBackWM+KUuvN2U5QWbl",
	"lsKb1/Yd0b5ra0xw0VaWMEJyS34Q5HG7SXW0vZYmxtScjNXeXhYEYbSWaspUaEkPiOhrW2o3lWEN+UNh",
	"vh9OBEkWRhvwEIa60K8PVfknQHI8RFZvhJUHY6bN57VWT56MHpVOf6uxO6xO5a3Eh850MvJNjLrqNOQM",
	"bD4YrMApHetBa4fT6VQbaA89HzwIorwfxmCPdmNOjuec1tb4UBqvetuRHW7UkVef8Katqo29gj170rFm",
	"A9Z6kmstpHfWvj6xtvOpHA5FeSbtreHUDhtT3Eewo6A5763mKtKGnWVNZ82uhPodqFrxVDHr7bW3NtfC",
	"RkJTDq5QbYIVS3KGsYTmvBF/r8/t8Ot43VfhOhQ1NhxJiiIOeNQzxL4iqdzIUIZbFa3rxtqSB3vtx6Qr",
	"i/Jq+ahxfX46RbK20gbjlew8zdD0SWjNx91WzxT77eH+YQ9Ui9fY5lZVmwjUUE+daGDsIDRRrbXJ9uvD",
	"fYuTaiY/jZs/nh5QNN96gaZq+8l6NzVUYTLk+6qJzAGcCkBBWgyxEE7Zeg2IVn2kar7ByhpELUFfC7Wn",
	"e5f6gMFUeZLb5f4hTUDo1/iF3f9BgL6kV74YfvHUZBsjG8MX4xAsXD4u5MrviVPn3856fuTIrrRv8dCu",
	"lJyPDv+Ddrt46NYk9mBpzELPrLhhUr4E0PBhyJD/3WQnc6VR5mlWkMctXhr8HMKRIHT97FaGFCJyjTQp",
	"I+GDDx13kx9zR4EcAhXGDhjTxcm5zjlm2ai/B2YfQYKRXJLzHMXZDojp1QaRl2U6ryDavebj24vCEcN2",
	"UBoEJsRF2AEYLKFZPFbjiMCyK2LSe4XzzifHrYTJAWr0Uo3SoIwJLd+NllYZYsEto6aJVHK6BUwO/LaX",
	"OBNqkbWFE4kTit6j5/xmiyDrw+hx4cixtosDF8ETsGsYH4EDRzfOXAEIA++FhrJxlnSdwMueuotD2Hs1",
	"ZOQuX9KY+ATsScT8HsCjE+8KU5Ne6nZkwqqVUiWiJwO99XQN4/R0vGN2pA8LlFx5GAq1vC9pQpvqx8sp",
	"8m81OlBU2uoSmaWNP9E0ZUhZk3IuXWp5xLoLB/olVv66HLT9+x5h9aFLkS45mg8doXIO5J3iQcrNNM+l",
	"F0LD9GKstFhYsOmJCUrNVEYyLfIFzNaCPmQgyDvmVSIPAeNwCH955vo/STGKNKCHVtoB81qiWK/Vw+M1",
	"jMmf5wrzWmVcP3lR0I/XKhO7UXLldHIdaEwse+Eu8OwOqcOTpDWttiVpd2ZK0oIPwXuSFwIKZiVtGBw4",
	"VuBUfgVXiU9Jcv41jAN6ZwzB2HTxn0JmC3D4jEMLOun9Bm9ZtSrzejzR08udj0zEa3a/NHWgJ0eJBYzr",
	"03ugAsaHhF2hvYEorqZ3fmeq/5oWEQmePgx9G27gpRPJ0tOgq8/4cNhXgSmLt9mRa1NguVtMOZ/yJwrg",
	"deTaFE//cgH7jI/PmI6a1vEI829zPY1pJTargI7HAyY/zyc4LhAdjfSMzzidkVg9v4EuIxrZQXoH8Gup",
	"bX7NgoXCs2d8zvyTGtHf/nF0ZDG9X8cP3e/S3G6PvCj0eyCQdrz0dH8h+Cc9bj3oFMxrmTv4Vf2tA61h",
	"fGEc4ktOPmH8b7Xrv9Wu/1a7/lvt+m+167/Vrt+52pXFGcTvvVPuOnZ53ubFHH79PpwaygR+9RYd0JaC",
	"YXO0vVRWC33bCNPI9jZc7gtDleRIp8Mh72PDkUAZIFQyUDHF+vX36ofPAMxW9y4lKwAEnWJ2cr4ImP+V",
	"XNiZXW58fEPAMGbSP5hi/6Pci298vZR3ARD83ptGkrDvGEtjsXz5up8bX+v9R5mNdth9MAZdbineX3P9",
	"4WL5H7Kr5JibSqKjl5la5NehKJQkkekNbDkDNy8dX8YeDieyJz7tgO+OvoInYXkN/zb/Oex78pcA23ua",
	"MlxkGQBjxi00PGWW6y9fhEBYLmAnHBtPK1Ef9TtAkezRFdwinf/w7PrcRL1mB9fz8/avf3z6S25GOOPE",
	"UxQieim6lzfOb2YiFovevOWn3YPi7QKhGwJEXkUoDKrp9Yk2NuGuml4qBp2A8aBPQJ/e02O4EQ7puei0",
	"2YsH/ReP3gLDsSy9edYPXyiw5PB0MhZ5x5UsFEVldwZNLJhiiCNHT65MSnFllhBDH6S3w4T59WI+8zOC",
	"fny4UrNKr+uOcJjdng5wnBbj/xz8hRaE7CCDn5ZLlj4EyTIGSG/WLAyfXmeV+agg2fVT4LxNLzeD9OoV",
	"ykRAmZdcA4Bsxw6ZP9PS0M52IocBCLlbaP4luTETGBY0j7YKFU4hPmVzGb8OqCayC13GTC7TPogxuePR",
	"Dsib5GKe7H6u15QOaP7vAqAAvl5C5Ui45cfy+4nSRSj8U5BoFr1f3w3shE04F9vvgVCqXWWo5Gf+n+oS",
	"GT+T4/E2u6NKG12tIbifqs77tzckWFVTBS+rUP8AfgDNgi89P2Y7O7y6zKXm1yad7wKrlt3imV/hWX73",
	"HEXmk+dzn5BOsc5BlpN+vF77uVAsuUY3W0JLY4p8++Q1juDPJNb/p7f5J/L+8h/gEJIlukf4xu342Zv0",
	"6qHiFdLHJhxiw49prxeAlq5vh5ZTuavIYxKtrmH8kn4ZwPFnNru8a/nF9VlLJm95KEkni85HCJ7p5QGT",
	"s7uYC3erFBcvbczodnh857iNQ7pWUzJnT3TzFz0ZfuGW5SoL6mkP04IJLEDXdelx5Ewett3/6KXF2NAO",
	"abCWv2ont723cxiVaiXftFrZcHTXgwcx8OzKXaV2y97WDkndP379+n8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
