# Terraform Provider testing workflow.
name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'SECURITY.md'
      - 'CODE_OF_CONDUCT.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'SECURITY.md'
      - 'CODE_OF_CONDUCT.md'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Lint, Build, Generate Docs & Acceptance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.16.1
          terraform_wrapper: false
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: latest
          install-only: true
      - name: Install dependencies
        run: make deps
      - name: Lint code
        run: make lint
      - name: Build code
        run: make build
      - name: Generate docs
        run: make generate
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make generate' command and commit."; exit 1)
      - name: Setup Workload Identity Federation
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Provider Acceptance tests
        env:
          F5ADS_CLIENT_ID: ${{ secrets.F5ADS_CLIENT_ID }}
          F5ADS_CLIENT_SECRET: ${{ secrets.F5ADS_CLIENT_SECRET }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: make testacc
